### ISSUE TITLE
Integration Request JSON Mapping Template

### ISSUE THREAD

**Issue by spencerfdavis** [awslabs/aws-apigateway-swagger-importer#102]
I'm trying to accomplish this with `RAML` in my `config.json` file and seems to be an issue with it.

I'm attempting to do something like this from the docs (http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html#input-variable-reference)
## Example JSON Mapping Template

The following example shows how to use a mapping to read a name from the query string and then include the entire POST body in an element:

```
{
  "name" : "$input.params('name')",
  "body" : $input.json('$')
}
```

but it my `config.json` wraps `$input.json('$')` in double quotes not passing on the body in `JSON` format.  I have it working on in API gateway manually but would like to use the importer which is not allowing me.

**Comment by pcutz** [comment]
Assuming that the RAML implementation is the same as swagger, you have to escape the quotation marks in your json definition, so that you'll get them on import.

This is what I'm doing in my swagger.json file:

```
"requestTemplates": {
      "application/json": "{\"name\": \"$input.params('name')\", \"body\": $input.json('$')}"
},
```

**Comment by spencerfdavis** [comment]
That did it @pcutz.  Thanks!
