### ISSUE TITLE
config cannot be loaded

### ISSUE THREAD

**Issue by phillip-haydon** [awslabs/aws-apigateway-swagger-importer#103]
This is in reference to #96

If the config file does not exist. 

https://github.com/awslabs/aws-apigateway-importer/blob/master/src/com/amazonaws/service/apigateway/importer/config/AwsConfig.java#L61

It will throw, 100% of the time. This means we cannot use environmental variables or anything.

It would be nice if there were command line arguments we can just pass in for this stuff and not have any dependencies on files for region etc.

**Comment by rpgreen** [comment]
If you specify the region parameter it will not attempt to load from the
file system.

On Monday, 30 November 2015, Phillip Haydon notifications@github.com
wrote:

> This is in reference to #96
> https://github.com/awslabs/aws-apigateway-importer/issues/96
> 
> If the config file does not exist.
> 
> https://github.com/awslabs/aws-apigateway-importer/blob/master/src/com/amazonaws/service/apigateway/importer/config/AwsConfig.java#L61
> 
> It will throw, 100% of the time. This means we cannot use environmental
> variables or anything.
> 
> It would be nice if there were command line arguments we can just pass in
> for this stuff and not have any dependencies on files for region etc.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/awslabs/aws-apigateway-importer/issues/103.

##

**Comment by phillip-haydon** [comment]
How can I specify it tho? I don't see that in the doco on the readme.

**Comment by rpgreen** [comment]
Use "--region [REGION]". You can see the parameters via "--help"

**Comment by phillip-haydon** [comment]
:+1: working great. Thanks. I'm gonna get a build of the jar (for windows) on nuget next week if you have no objections.
