### ISSUE TITLE
Adding the ability use use environment variable to configure credentials

### ISSUE THREAD

**Issue by AlexisNo** [awslabs/aws-apigateway-swagger-importer#108]
It would be nice to be able to use environment variables to [configure credentials like for the aws-cli](http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-environment).

**Comment by rpgreen** [comment]
This is possible with a recent change. Please update and see http://docs.aws.amazon.com/AWSSdkDocsJava/latest/DeveloperGuide/credentials.html for information
