### ISSUE TITLE
Automatically create the lambda permissions on api create / update

### ISSUE THREAD

**Issue by mpuittinen** [awslabs/aws-apigateway-swagger-importer#111]
Add capability to create the Lambda permissions on the fly (as the console does) when importing new APIs. This would simplify API creation a lot.

**Comment by ajagnanan** [comment]
+1

**Comment by aviflax** [comment]
+1

**Comment by jackrk** [comment]
Yep, this is being considered. It's in our backlog at the moment. 

Thanks for the feedback!

**Comment by cheekymonkat** [comment]
+1

**Comment by nsutcliffe-speedline** [comment]
+1

**Comment by shikasta-kashti** [comment]
+1

**Comment by mikerahmati** [comment]
+1

**Comment by cosbor11** [comment]
+1

Yea, this a huge pain point in the process

**Comment by charleswhchan** [comment]
+1

**Comment by lony** [comment]
+1

**Comment by romain-nio** [comment]
+1

**Comment by rdewaele** [comment]
+1

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan
