### ISSUE TITLE
Deploy jar-with-dependencies to Maven Central and in GitHub releases

### ISSUE THREAD

**Issue by moshen** [awslabs/aws-apigateway-swagger-importer#114]
As of now, only the "regular" jar is deployed to Maven Central: http://search.maven.org/#artifactdetails%7Ccom.amazonaws%7Caws-apigateway-importer%7C1.0.1%7Cjar

By deploying the built uber-jar, you enable easier distribution and usage.

**Comment by jjmartin** [comment]
:+1:   Please also post the latest updates, the last version was from 11/10

**Comment by jackrk** [comment]
Hi, we're working on getting the latest updates released. ETA is by end of week.

**Comment by petemounce** [comment]
:+1: This would be _really_ useful for us, too. Specifically, I'd like to be able to download the standalone JAR from somewhere (like github releases), rather than need to compile it myself.

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan
