### ISSUE TITLE
integrationResponse - selectionPattern isn't copied from JSON

### ISSUE THREAD

**Issue by jjmartin** [awslabs/aws-apigateway-swagger-importer#115]
my responses looks like this:

```
 "responses": {
                        "200": {
                            "responseTemplates": {
                                "application/json": null
                            },
                            "statusCode": "200"
                        },
                        "404": {
                            "selectionPattern": ".*Not Found.*",
                            "statusCode": "404"
                        }
                    }
```

but line 277 of ApiGatewaySdkSwaggerApiImporter.java is selecting the key of the section as the value here: 
`.withSelectionPattern(pattern);`

so when deployed, my integration responses looks like: (from CLI) 

```
"integrationResponses": {
        "200": {
            "responseTemplates": {
                "application/json": null
            },
            "selectionPattern": "200",
            "statusCode": "200"
        },
        "404": {
            "selectionPattern": "404",
            "statusCode": "404"
        }
    }
```

Is there some reason behind this?  i can submit the pull request if that would just fix it, but i don't know how it would affect non-lambda backed methods... (or if the selectionPattern is missing as the case is for my 200)

**Comment by jjmartin** [comment]
ok i see one of my problems is that you are using the 200 as the selectionPattern but the CLI/API returns the values differently than your example doc seems to take them.

it seems kind of weird to do it that way..most of the other stuff i can just pull from the CLI for getting my existing API documented, but this section is odd..  (there also isn't anything in the readme explaining how this works... )

**Comment by jjmartin** [comment]
I was able to get the result i wanted by re-arranging the values.

```
"responses": {
                        "default": {
                            "responseTemplates": {
                                "application/json": null
                            },
                            "statusCode": "200"
                        },
                         ".*Not Found.*": {
                             "responseTemplates": {
                                "application/json": null
                            },
                            "statusCode": "404"
                        }
                    }
```

**Comment by jackrk** [comment]
I agree that the discrepancy is a little weird. We are working on better documentation both on the service and this tool, so we'll make sure to address this. 

Thanks,

Jack
