### ISSUE TITLE
Responses using $ref not being imported

### ISSUE THREAD

**Issue by joshua-peterson-volusion** [awslabs/aws-apigateway-swagger-importer#117]
I have several common responses that I have defined under responses in my yaml.  I am then referencing them in my header definitions.  Like this:

```
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/NoResult"
        '404':
          $ref: "#/responses/404"
        '500':
          $ref: "#/responses/500"
```

In api gateway, the method response shows the status code, but the headers and models are not being imported.  If I copy/paste the response directly into the operation they import fine.  Are $refs supported for responses?

**Comment by rpgreen** [comment]
Please correct me if I'm wrong, but I believe Swagger only allows $refs for model schemas and not for arbitrary objects in the Swagger definition. As such, there is no plan to support this.

**Comment by joshua-peterson-volusion** [comment]
According to swagger documentation reuse via refs are supported for:

> The following types are reusable, as defined by the spec:
> 
> Operations
> Parameters
> Responses
> Models (or Schema Objects in general)

https://github.com/swagger-api/swagger-spec/blob/master/guidelines/REUSE.md

**Comment by rpgreen** [comment]
Thanks - it seems that the refs aren't getting parsed. I think the fix may be in swagger-parser but I'll take a deeper look.

**Comment by jjmartin** [comment]
i think this may be the same as https://github.com/awslabs/aws-apigateway-importer/issues/112

**Comment by neogeo** [comment]
A fix for this would be very helpful, as it would limit redundancy in the swagger file.

**Comment by doapp-ryanp** [comment]
+1 to this would be very helpful especially for [CORS config](http://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-cors.html#enable-cors-for-resource-using-swagger-importer-tool)

**Comment by nsutcliffe-speedline** [comment]
+1

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan
