### ISSUE TITLE
Stage Variable As Lambda Alias Breaks APIG Dashboard Test

### ISSUE THREAD

**Issue by austencollins** [awslabs/aws-apigateway-swagger-importer#119]
Hi Ryan, 

I hope things are well with you.  I'm wondering if you could confirm a bug.  When we point APIG Endpoints to a Lambda that uses an API Gateway Stage Variable as the Lambda's Alias, we can't test the Endpoint in the APIG dashboard because it throws a regular expression error.

Full Example ARN:

```
arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:101010101:function:austen4-UsersImages:${stageVariables.functionAlias}/invocations
```

Throws this error:

```
{
  "message": "1 validation error detected: Value 'arn:aws:lambda:us-east-1:101010101:function:austen4-UsersImages:' at 'functionName' failed to satisfy constraint: Member must satisfy regular expression pattern: (arn:aws:lambda:)?([a-z]{2}-[a-z]+-\\d{1}:)?(\\d{12}:)?(function:)?([a-zA-Z0-9-_]+)(:(\\$LATEST|[a-zA-Z0-9-_]+))?"
}
```

Are we doing something wrong with how we are entering in the Stage Variable?

**Comment by rpgreen** [comment]
Hi Austen,

I think I responded to your forum post yesterday. This is a known issue with the console - we're working on it. You can still test with the SDK/CLI. If invocation works after you deploy the API then you are using stage variables correctly. -Ryan

**Comment by austencollins** [comment]
Saw the post.  As always, you are the man.  Thanks Ryan :)
