### ISSUE TITLE
requestParameters under "x-amazon-apigateway-integration"

### ISSUE THREAD

**Issue by snafufansbbc** [awslabs/aws-apigateway-swagger-importer#12]
I'm confused about how this 'requestParameters' section relates to the 'parameters' section under 'get'.

Specifically, looking at https://github.com/awslabs/aws-apigateway-swagger-importer/blob/master/tst/resources/apigateway.json you have:

"requestParameters" : {
                        "integration.request.path.integrationPathParam" : "method.request.querystring.latitude",
                        "integration.request.querystring.integrationQueryParam" : "method.request.querystring.longitude"
}

which seems to imply that you could only have one path param and one query param.

In the 'parameters' section just above this in apigateway.json, both latitude and longitude are actually specified as "in": "query".

Is there any documentation for these x-amazon extensions other than the examples under tst/?

**Comment by rpgreen** [comment]
The requestParameters define how you map your operation parameters to your backend integration. If you have an HTTP integration, it may require different parameters than your API. The requestParameters section allows you to map parameters from your Swagger-defined API to your backend integration path, query string, or header. 

You can have any number of requestParameters defined. 

Similarly, responseParameters allows you to map to method response parameters (headers).

Better documentation on this is on the way!

**Comment by koxon** [comment]
Hi,

I can't manage to list several integration.request.querystring.integrationQueryParam
If I list several of them, only the last one is picked up.
If I try an array, it fails.

Could we please have a snipet on how to list several requestParameters ?

thanks
