### ISSUE TITLE
Client-Side SSL Authentication

### ISSUE THREAD

**Issue by maruks** [awslabs/aws-apigateway-swagger-importer#122]
is it possible to setup Client-Side SSL Authentication for AWS gateway?    

http://docs.aws.amazon.com/apigateway/latest/developerguide/getting-started-client-side-ssl-authentication.html

**Comment by maruks** [comment]
please add support for Client-Side SSL Authentication

**Comment by jackrk** [comment]
The Client-Side SSL feature is arguably out-of-scope for the swagger importer, similar to setting up CloudWatch logging as mentioned here: https://github.com/awslabs/aws-apigateway-importer/issues/124

The SSL Cert itself has to be setup on the account level which you could use the CLI to do. Linking the cert to a RestApi is done on the stage settings, but the importer only supports a basic deployment right now. Managing stage settings is easy using the console or the CLI, and a patch on the deployment code in the importer could also do the trick if more parameters are passed in.

**Comment by jackrk** [comment]
Also check out this comment on a related issue: 

https://github.com/awslabs/aws-apigateway-importer/issues/124#issuecomment-164859378

References a PR by @cfair that would do the trick for you if this is blocking you.
