### ISSUE TITLE
Error loading AWS configuration for region

### ISSUE THREAD

**Issue by Shockolate** [awslabs/aws-apigateway-swagger-importer#130]
The importer fails when trying to import swagger.json.
I get the error:

``` bash
$ ./aws-api-import.sh --create ../swagger.json
 ERROR - Could not load region from profile and no region parameter specified
```

after knowing for certain that my aws cli is configured:

``` bash
$ aws configure
AWS Access Key ID [********************]:
AWS Secret Access Key [**********************]:
Default region name [us-east-1]:
Default output format [json]:
```

Note: I am able to use other functions successfully with the AWS CLI.

**Comment by koxon** [comment]
configure aws cli first
ᐧ

On Tue, Dec 22, 2015 at 11:18 AM, Ted Armstrong notifications@github.com
wrote:

> The importer fails when trying to import swagger.json.
> I get the error:
> 
> $ ./aws-api-import.sh --create ../swagger.json
> ERROR - Could not load AWS configuration. Please run 'aws configure'
> 
> after knowing for certain that my aws cli is configured:
> 
> $ aws configure
> AWS Access Key ID [*******************_]:
> AWS Secret Access Key [**_*******************]:
> Default region name [us-east-1]:
> Default output format [json]:
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/awslabs/aws-apigateway-importer/issues/130.

## 

Nicolas Menciere
Co-Founder and CTO
Sport Archive Inc.

**Comment by Shockolate** [comment]
@koxon 
My AWS CLI was configured first.

**Comment by lorenzoaws** [comment]
Hi Ted, I'm sorry you're having issues with the tool. While we investigate this, can you confirm whether passing the region in explicitly in the command works around the issue?

i.e.:
`$ ./aws-api-import.sh --create ../swagger.json --region us-east-1`

**Comment by Shockolate** [comment]
@lorenzoaws 
Passing the region in explicitly does workaround the issue

**Comment by lorenzoaws** [comment]
OK great, what about passing in the profile instead? I'm guessing this will fail because this is what we do by default.

`$ ./aws-api-import.sh --create ../swagger.json --profile default`

If this does fail, can you try creating and passing in a new profile?

**Comment by Shockolate** [comment]
@lorenzoaws 
Sorry for my delayed response, I've been on break.
Please see my attempted queries (I don't think the crashing readlink is related) :

``` bash
$ ./aws-api-import.sh --update <API_ID> --deploy stage ../apigateway/swagger.json
      0 [main] readlink 38336 open_stackdumpfile: Dumping stack trace to readlink.exe.stackdump
2015-12-28 11:45:38,468 ERROR - Could not load region from profile and no region parameter specified. Please run 'aws configure' or specify region with '--region' parameter.

username@COMPUTERNAME /d/git/aws-apigateway-importer (master)
$ ./aws-api-import.sh --update <API_ID> --deploy stage ../apigateway/swagger.json  --profile default
      0 [main] readlink 47324 open_stackdumpfile: Dumping stack trace to readlink.exe.stackdump
2015-12-28 11:46:07,878 ERROR - Could not load region from profile and no region parameter specified. Please run 'aws configure' or specify region with '--region' parameter.

username@COMPUTERNAME /d/git/aws-apigateway-importer (master)
$ aws configure --profile test_user
AWS Access Key ID [None]: <Same_Access_Key_ID_as_Default>
AWS Secret Access Key [None]: <Same_Secret_as_Default>
Default region name [None]: us-east-1
Default output format [None]: json

username@COMPUTERNAME /d/git/aws-apigateway-importer (master)
$ ./aws-api-import.sh --update <API_ID> --deploy stage ../apigateway/swagger.json  --profile test_user
      0 [main] readlink 54496 open_stackdumpfile: Dumping stack trace to readlink.exe.stackdump
2015-12-28 11:48:00,607 ERROR - Could not load region from profile and no region parameter specified. Please run 'aws configure' or specify region with '--region' parameter.
```

**Comment by koxon** [comment]
Environment variable:
AWS_DEFAULT_REGION=us-east-1

Does the trick for me.

ᐧ

On Mon, Dec 28, 2015 at 2:49 PM, Ted Armstrong notifications@github.com
wrote:

> @lorenzoaws https://github.com/lorenzoaws
> Sorry for my delayed response, I've been on break.
> Please see my attempted queries (I don't think the crashing readlink is
> related) :
> 
> $ ./aws-api-import.sh --update <API_ID> --deploy stage ../apigateway/swagger.json
>       0 [main] readlink 38336 open_stackdumpfile: Dumping stack trace to readlink.exe.stackdump
> 2015-12-28 11:45:38,468 ERROR - Could not load region from profile and no region parameter specified. Please run 'aws configure' or specify region with '--region' parameter.
> 
> username@COMPUTERNAME /d/git/aws-apigateway-importer (master)
> $ ./aws-api-import.sh --update <API_ID> --deploy stage ../apigateway/swagger.json  --profile default
>       0 [main] readlink 47324 open_stackdumpfile: Dumping stack trace to readlink.exe.stackdump
> 2015-12-28 11:46:07,878 ERROR - Could not load region from profile and no region parameter specified. Please run 'aws configure' or specify region with '--region' parameter.
> 
> username@COMPUTERNAME /d/git/aws-apigateway-importer (master)
> $ aws configure --profile test_user
> AWS Access Key ID [None]: <Same_Access_Key_ID_as_Default>
> AWS Secret Access Key [None]: <Same_Secret_as_Default>
> Default region name [None]: us-east-1
> Default output format [None]: json
> 
> username@COMPUTERNAME /d/git/aws-apigateway-importer (master)
> $ ./aws-api-import.sh --update <API_ID> --deploy stage ../apigateway/swagger.json  --profile test_user
>       0 [main] readlink 54496 open_stackdumpfile: Dumping stack trace to readlink.exe.stackdump
> 2015-12-28 11:48:00,607 ERROR - Could not load region from profile and no region parameter specified. Please run 'aws configure' or specify region with '--region' parameter.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/awslabs/aws-apigateway-importer/issues/130#issuecomment-167639458
> .

## 

Nicolas Menciere
Co-Founder and CTO
Sport Archive Inc.

**Comment by lorenzoaws** [comment]
@koxon. Interesting, what environment are you running in?
@Shockolate It looks like you're on a Windows machine running Cygwin? Does the environment variable trick work for you?

**Comment by Shockolate** [comment]
@lorenzoaws 
Adding the environment variable does not work for me. I'm running these commands (and the AWS CLI) with the Git Bash window (with ruby and ruby dev kit)

**Comment by koxon** [comment]
I'm on Linux.
See:
http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-environment

You can also use the configuration file:
http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-config-files

ᐧ

On Mon, Dec 28, 2015 at 3:51 PM, Ted Armstrong notifications@github.com
wrote:

> @lorenzoaws https://github.com/lorenzoaws
> Adding the environment variable does not work for me. I'm running these
> commands (and the AWS CLI) with the Git Bash window (with ruby and ruby dev
> kit)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/awslabs/aws-apigateway-importer/issues/130#issuecomment-167653192
> .

## 

Nicolas Menciere
Co-Founder and CTO
Sport Archive Inc.

**Comment by lorenzoaws** [comment]
@Shockolate : It might be related to readline. Can you try pulling this change to see if it works for you? 
https://github.com/awslabs/aws-apigateway-importer/pull/133/files

**Comment by Shockolate** [comment]
@lorenzoaws 
I pulled the change, but the issue remains

``` bash
user@COMPUTER /d/git/aws-apigateway-importer (PullRequest133)
$ ./aws-api-import.sh --update <API_ID> --deploy stage ../apigateway/swagger.json
2015-12-29 10:47:00,038 ERROR - Could not load region from profile and no region parameter specified. Please run 'aws configure' or specify region with '--region' parameter.
```

**Comment by kahouieong** [comment]
@Shockolate 
We apologize that you cannot use the region setting from your profile. We found the issue with loading region from the different environments. We will prioritize this issue in our backlog. As workaround, please use the '--region' parameter.

**Comment by rpgreen** [comment]
@Shockolate 

Please use "--profile test_user" or "--region us-east-1". Reopen if still experiencing issues

**Comment by Shockolate** [comment]
@rpgreen 

specifying the region with `--region` does work and how I will be working around the issue.

The `--profile test_user` does not work.
