### ISSUE TITLE
Please deploy on maven central

### ISSUE THREAD

**Issue by rpiskule** [awslabs/aws-apigateway-swagger-importer#138]
1.0.1 is released, but 1.0.2 is not released. Please be sure to keep maven central up to date.

Thanks,
-Rob

**Comment by rpgreen** [comment]
In progress

**Comment by rpiskule** [comment]
Any luck on this? I could really use the newer version that uses the provider chain & not forces the use of profiles.

Thanks,
-Rob

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan
