### ISSUE TITLE
basePath behaviour doesn't appear to match Swagger UI expectations

### ISSUE THREAD

**Issue by hotchkj** [awslabs/aws-apigateway-swagger-importer#140]
I'm hoping to get clarification on why the importer tool uses basePath in the way it does, and whether this is intended to work with usual Swagger tools. There seems to be a mismatch, which would be great to resolve.

Currently, the importer adds basePath as part of the generated API operations. This is confusing to me for a few reasons. Lets' say that basePath is `testing` and host is `my.domain`.
- In order to create 'Try It Out' URLs from the YAML, Swagger UI must concatenate host, basePath and the actual path to create the final call e.g. https://my.domain/testing/myoperation
  - The entire point of this is that the documentation is built directly from the Swagger YAML
- API Gateway introduces a further path fragment as part of Stages e.g. a Stage of prod will produce a URL of https://my.domain/prod/testing/myoperation
- Export from API Gateway produces non-standard Swagger YAML (host must be the host only and does not include the scheme nor sub-paths) e.g.: `host: "my.domain/prod"` which the standard Swagger tools (UI & Editor) seem to refuse to load.

It seems like one fix would be that for API Gateway, the basePath should represent the stage, and be ignored during basic import.

To my mind, this would have several benefits - API Gateway & Swagger UI would play nicely together, one could maintain different Swagger files for different stages without issue, thus neatly documenting each stage independently, and at some later date, the importer could be extended to perform a Stage operation without much additional command line complexity.

However, I may be missing something totally obvious - thoughts appreciated & thanks for a great tool!

**Comment by rpgreen** [comment]
These are good points. Currently the importer and the export functionality have differing conventions on how basePath is used. We plan to make this consistent soon.

I don't think that our customers want to maintain different swagger files for different stages - we have aimed previously to decouple the API definition from deployments.

As you said, the solution may be to simply use basePath to represent the stage and ignore it on import. This will allow compatibility with swagger tools and also with the export operation. Of course, this would be a backwards-incompatible change. Appreciate any more thoughts on this.

Thanks,
Ryan

**Comment by hotchkj** [comment]
Glad to hear that the import & export will become consistent.

The most flexible approach that comes to mind would be something like a command line option of `--ignorebasepath /api` or `--stage /api` and if e.g. the file's basePath is `/api/v1`, the tool does 'look for first substring in basePath and remove if present', or something like that. That way existing behaviour is preserved but users can choose to control basePath behaviour. Alternatively just `--ignorebasepath` and it's just skipped as host is, or make a breaking change. It does seem like basePath is something that would be handled at the Deploy Stage & Custom Domain Name level in API Gateway.

On the subject of different swagger files, I wanted to outline my thinking about how a team would use these files coupled with source control (it's required for us that every version and every stage of an API be in source control, as well as accurately documented when deployed), and see whether that marries up with the wider intent of API Gateway & Swagger.

I agree that people don't want to maintain whole separate files per stage, but I'm thinking more along the lines of multiple top-level files referencing the same API definitions (an example being at https://github.com/ex-nerd/swagger-example/blob/master/swagger/index.yaml)

I might have in git:
- apiv1paths.yaml
- apiv1definitions.yaml

These are destined for an API in Gateway imaginatively name APIV1, but by themselves aren't enough to correctly write a complete Swagger file for import.

In deployment I might have:
- staging/apiv1.yaml - has basePath & host set up for staging
- prod/apiv1.yaml - has basePath & host set up for prod

These use $ref to bring in the actual API. Combining these with the YAML files from a given build artifact gives me the complete API definition I'm deploying - I can point Swagger UI straight to that YAML file and get the precise documentation for that deployment. One of these files I need to import to Gateway in order to then deploy it to the matching stage.

Does that make sense? I'm absolutely open to different approaches, as long as I can end up with each final host & basePath matching the deployed API in a given stage.

**Comment by awendt** [comment]
I ran into the same issue. I set up a tiny API in the AWS Console, then exported stage "staging" and used CI to import into stage "ci." Suddenly I had everything on stage "ci" prefixed with "/staging" because of `basePath`. It seems like `basePath` is silently ignored if it matches the stage name.

Sketching our use-case: We don't want to maintain different YAML files for different stages. Instead, we'd like to continuously import the API from source control into stage "ci", then proceed selected deployments to stage "staging" and finally production.

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan
