### ISSUE TITLE
Possible to create resources such that they require an API Key?

### ISSUE THREAD

**Issue by aviflax** [awslabs/aws-apigateway-swagger-importer#145]
I’m using RAML and I’d like to set the “API Key Required” setting of each resource to true. I don’t see anything in the source code or the examples for this… am I missing it or is it just not currently supported? If not, please consider this a feature request!

Thank you!

**Comment by aviflax** [comment]
Ah, I see that the setting is actually on each method, rather than resource, and part of the “method request” aspect of a method.

**Comment by rpgreen** [comment]
Yes this is possible. Take a look at https://github.com/awslabs/aws-apigateway-importer/blob/master/tst/resources/swagger/apigateway.json

Notice the security definition for "api_key", which can be enabled at the API or method level via

```
                "security" : [{
                    "api_key" : []
                }],
```

**Comment by aviflax** [comment]
Thanks Ryan. Does this work identically with RAML? Also it's a little odd that an empty array equates to "true" — what's up with that?

Thanks!

**Comment by aviflax** [comment]
Yeah it’s really not clear to me how this would map to RAML, since `security` seems to be a “native” Swagger property… would the importer understand RAML’s `securityScheme` concept? I’m a little dubious…

**Comment by rpgreen** [comment]
AFAIK it's not implemented for RAML. There's another issue open on this.

On Wednesday, 13 January 2016, Avi Flax notifications@github.com wrote:

> Yeah it’s really not clear to me how this would map to RAML, since
> security seems to be a “native” Swagger property… would the importer
> understand RAML’s securityScheme concept? I’m a little dubious…
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/awslabs/aws-apigateway-importer/issues/145#issuecomment-171409009
> .

##

**Comment by aviflax** [comment]
@rpgreen OK, thanks!
