### ISSUE TITLE
References are incorrectly resolved causing infinate recursion ignoring the full JsonPointer

### ISSUE THREAD

**Issue by DALDEI** [awslabs/aws-apigateway-swagger-importer#147]
Using a swagger YAML file which has an embedded property of the same name as a top level property in the definition section causes infintate recursion.
This appears to be do to getSchemaName ignoring the reference value path  

``` java
 public static String getSchemaName(String refVal) {
        String schemaName;
        try {
            schemaName = refVal.substring(refVal.lastIndexOf("/") + 1,
                                          refVal.length());
        } catch (Throwable t) {
            throw new IllegalStateException("Invalid reference found: " + refVal, t);
        }

        return schemaName;
    }
```

Taking only the basename

And always appling '#/definitions' to resolve all references

``` java
    private void replaceRef(ObjectNode parent, String schemaName) {
        LOG.debug("replaceRef: " + parent.toString()  + " with " + schemaName );
        parent.set("$ref", new TextNode("#/definitions/" + schemaName));
    }

```

( the LOG statements are mine) 

With the attached swagger , attemping to import using      -c recurse.yaml

THe following is repeated until the stack is exaustred

``` log
DEBUG [main] (SchemaTransformer.java:51) - buildSchemaReferenceMap{"description":"defined in definitions","$ref":"#/definitions/endpoint"}
DEBUG [main] (SchemaTransformer.java:62) - replaceRef:  {"description":"defined in definitions","$ref":"#/definitions/endpoint"} : endpoint
DEBUG [main] (SchemaTransformer.java:132) - replaceRef: {"description":"defined in definitions","$ref":"#/definitions/endpoint"} with endpoint
DEBUG [main] (SchemaTransformer.java:51) - buildSchemaReferenceMap{"description":"defined in definitions","$ref":"#/definitions/endpoint"}
DEBUG [main] (SchemaTransformer.java:62) - replaceRef:  {"description":"defined in definitions","$ref":"#/definitions/endpoint"} : endpoint
DEBUG [main] (SchemaTransformer.java:132) - replaceRef: {"description":"defined in definitions","$ref":"#/definitions/endpoint"} with endpoint
DEBUG [main] (SchemaTransformer.java:51) - buildSchemaReferenceMap{"description":"defined in definitions","$ref":"#/definitions/endpoint"}
```

( file renamed as .txt so it could be attached)

[recurse.yaml.txt](https://github.com/awslabs/aws-apigateway-importer/files/102006/recurse.yaml.txt)

I believe the relevent part is 

``` yaml

definitions:

  recurse:
    description: references a defined object of the same name
    type: object
    properties:
      endpoint:
        description: defined in definitions
        $ref: '#/definitions/endpoint'

  endpoint:
    type: object
    description: A REST Endpoint
    properties:
      host:
        type: string
      path:
        type: string

```

When resolving #/definitions/recurse/endpoint  its resolving back to itself instead of finding #/definitions/endpoint

Note: this validates with swagger-validator

**Comment by rpgreen** [comment]
The schema certainly looks valid. Seems to be a bug - thanks for reporting. If you can get around to sending a PR I will merge it in

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan
