### ISSUE TITLE
Too Many Requests

### ISSUE THREAD

**Issue by rpiskule** [awslabs/aws-apigateway-swagger-importer#149]
Often when running longer APIs JSON files, we get "Too Many Requests" exception-- such as two jenkins jobs deploying separate APIs (such as for two different developers).

**Comment by rpgreen** [comment]
There is a per-account throttling limit applied to the API Gateway API.

The importer client will know to backoff and retry when throttled, but if you're running multiple imports concurrently it's expected that you will see throttling errors.

Your options:

1) Use a lock on the Jenkins jobs so they can't run concurrently
2) Use separate accounts for each API
3) Modify the importer to increase the maximum number of throttling retries
4) Add delays to the importer to minimize possibility for throttling

**Comment by HyperBrain** [comment]
@rpgreen We still face the problem with an API consisting of many resources even if running only on exactly one job. The importer should intercept any 429 HTTP results and just use some dynamic delay between GW API calls to overcome the throttling issue. Please reopen the issue.

**Comment by HyperBrain** [comment]
@rpgreen I added a PR for the issue. Could you please review - in my opinion there might be a lot of people affacted, especially when they deal with APIs with a lot of resources (e.g. we have one with more than 40 resources where the error was permanently thrown before the fix)

**Comment by arabold** [comment]
+1 This is a serious problem and showstopper. Since we have added five more resources to a total of about 45, the importer stopped working as it always abouts with a "Too Many Requests" exception.

**Comment by rpgreen** [comment]
Thanks for bringing this to our attention. This is definitely not the expected behavior. We will investigate - in the meantime I would suggest adding some backoff/retry logic such as in https://github.com/awslabs/aws-apigateway-importer/issues/156

**Comment by rpgreen** [comment]
Do you see this error consistently? I am able to reproduce the 429 errors, but not able to exceed the maximum number of retries.

Can you send a sample Swagger file to reproduce?

FYI, the default retry policy can be tuned here: https://github.com/awslabs/aws-apigateway-importer/blob/master/src/com/amazonaws/service/apigateway/importer/config/ApiImporterDefaultModule.java#L63

If you can send a PR which extends SDKDefaultBackoffStrategy with tuned values that work for you, I would be happy to merge

**Comment by HyperBrain** [comment]
@rpgreen Could it be that the core SDK just does not react on the 429-TooManyRequestsException and thus returns false for shouldRetry() ?
See here: https://www.codatlas.com/github.com/aws/aws-sdk-java/9403ad7/aws-java-sdk-core/src/main/java/com/amazonaws/retry/RetryUtils.java?line=32
With the fix applied in my PR I saw that the throttling occured 2 times but was circumvented after exactly one retry. So it also should be that way with the core throttling handling.

**Comment by rpgreen** [comment]
It's definitely retrying - you can observe it in a debugger. The error code
is "ThrottlingException" so isThrottlingException() is returning true.
Unless of course you are experiencing a different service error from what
I'm seeing, but that's not likely.

**Comment by rpiskule** [comment]
@rpgreen
It definitely happens to us even when we are running a single job. Our job creates about 130 different resources.

I can send our API, but because it is company owned code, I'd probably have to send it to your AWS e-mail account. Alternatively, I can open up an issue on our AWS business support and attach the file there.

**Comment by arabold** [comment]
Same here. For us it seems to work if I run it on my local PC, as it's just not as fast and with such a good network connection as the build server which sits inside of the same Amazon region we're deploying to. I can send you our json, but I won't be able to post it publicly on GitHub.

**Comment by rpiskule** [comment]
@rpgreen
I have filed an urgent support case to AWS.
Case ID 1642842121

**Comment by rpgreen** [comment]
I just pushed a few fixes to increase the backoff time and rate limit some of the calls. Can you guys pull the latest and let me know how that goes?

If still having issues, you can tune the backoff parameters at:

https://github.com/awslabs/aws-apigateway-importer/commit/10fba00d6b90501bf93f18a506f48196ba5a6b10#diff-29fabed39931b153aceef7b47e6376f2R90

**Comment by rpiskule** [comment]
@rpgreen
I will try it, but it will take a few days to know if it is exactly right. Thanks.
