### ISSUE TITLE
Suggestion: Create a release package for aws-apigateway-importer

### ISSUE THREAD

**Issue by charleswhchan** [awslabs/aws-apigateway-swagger-importer#153]
For teams who are not using Java as their native development environment, it is fair easier to use the tool if the necessary .sh and .jar generated from `mvn assembly` is provided as a release package.

FYI: We are using Python, boto/boto3. This tool is a huge time saver, would be nice if there was a Python version of the tool!

**Comment by koxon** [comment]
Use the Docker image :)

**Comment by hello-josh** [comment]
@koxon `s/Java/Docker/g` and it is still relevant

For teams who are not using Docker in their toolchain, it is far easier to use the tool if the necessary .sh and .jar generated from mvn assembly is provided as a release package.

**Comment by rpgreen** [comment]
"Release package" could mean different things in different environments - can you be more specific about what you'd like to see?

**Comment by hello-josh** [comment]
I can't speak for the OP but something that doesn't require maven or a build tool would satisfy the criteria for me.

**Comment by charleswhchan** [comment]
My requirement is basically the same as @Trii. 

Right now, I have a job that runs Maven to compile the, and then I have a script create a .tar.gz with the following files:
- aws-api-import.cmd
- aws-api-import.sh
- target/aws-apigateway-importer-1.0.3-SNAPSHOT-jar-with-dependencies.jar

In my CD job, I extract the contents of the .tar.gz and call aws-api-import.

**Comment by rpgreen** [comment]
This sounds like a reasonable solution for now. You could also take a direct dependency on the pre-built jar in Maven central.

We have some things coming out soon which will help with this - stay tuned

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan
