### ISSUE TITLE
Minor issues with --help

### ISSUE THREAD

**Issue by charleswhchan** [awslabs/aws-apigateway-swagger-importer#154]
When running apigateway-importer without any args, the output is slightly misaligned:
1. `--help` and `--raml-config` have an extra indent
2. weird description for `--help`; blank line (description?) and extra `Default: false`

```
Usage: aws-api-import [options] Path to API definition file to import
  Options:
    --create, -c
       Create a new API
       Default: false
    --deploy, -d
       Stage used to deploy the API (optional)
        --help

       Default: false
    --profile, -p
       AWS CLI profile to use (optional)
       Default: default
        --raml-config
       RAML file for API Gateway metadata (optional)
    --region, -r
       AWS region to use (optional)
    --test, -t
       Delete the API after import (create only)
       Default: false
    --update, -u
       API ID to import swagger into an existing API
```

**Comment by jackrk** [comment]
Agreed, that doesn't look right. I'll take a look at fixing this for a future release. Thanks for pointing this out.

**Comment by charleswhchan** [comment]
Thanks @jackrk!

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan
