### ISSUE TITLE
Problems with host and basePath

### ISSUE THREAD

**Issue by franksl** [awslabs/aws-apigateway-swagger-importer#167]
Hello,
I noticed some problems in the interpretation of the host and basePath parameters.
Suppose I have a gateway stage named mystage for the api api.example.com and a base path /v1.
A possible url could be: https://api.example.com/mystage/v1/myresource

To be able to generate correct documentation from the swagger file I should use this configurations:
host: "api.example.com"
basePath: "/mystage/v1"

But this arises a problem: when I use the importer it creates a "mystage" resource under root and when I deploy the api the final url becomes: 

https://api.example.com/mystage/mystage/v1/myresource 

which is wrong because of the double "mystage" resource.

The aws gateway exporter in the aws console resolves this problem by putting the stage name in the host parameter, like this:
host: "api.example.com/mystage"
basePath: "/v1"

but the problem with this configuration is that the host parameter written this way breaks the swagger 2.0 specifications (https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/2.0.md).

How could this be resolved? As a hint, if I recall correctly, version 1.2 of the importer did not have this problem but I could be wrong.
I hope I explained myself sufficiently,
Thanks,
Franco

**Comment by rpgreen** [comment]
Hi Franco,

Thanks for reporting. This is a known incompatibility between the exporter and importer. Currently the importer assumes the deployment stage is not a part of the API definition.

The API Gateway concept of Stage is not something that maps directly to the Swagger spec.

We're thinking of using the basePath field exclusively for the deployment stage for import and export, and enforcing that it can be only a single path element.

Any resource base path elements would need to be prepended in the individual paths.

Does this make sense? What would your preferred behavior be?

**Comment by franksl** [comment]
Hi, thanks for the answer. Sorry, I didn't know this was already known.
What do you think about adding an extension for the deployment stage? For example it could be stripped from the basePath to create resources.
For example something like:
host: api.example.com
basePath: /mystage/v1
x-aws-deployment-stage: /mystage

this would strip "/mystage" from the basePath and create resources starting from "/v1".
Generated documentation would be correct and to my knowledge will comply to swagger specification.
Thanks,
Franco

**Comment by rpgreen** [comment]
That wouldn't work as the generated documentation and tools built on the Swagger spec would be incorrect - the URL generated wouldn't include the stage, which is required to invoke an API.

**Comment by franksl** [comment]
Sorry, I don't follow you, to my knowledge the generated documentation would ignore the x- parameter  and the final url would be something like:

https://api.example.com/mystage/v1/my_resource

on both the documentation and the deployed api...

The x parameter would be used by the importer just to create resources on the api gateway and create the correct url at deployment.
Franco

**Comment by rpgreen** [comment]
Sorry I didn't see that you had the stage in the basePath as well.

Yes I think it makes sense to include the stage name as the first element of basePath. I'm not sure if we need the extension at all in that case. We might want to have a flag in the importer to opt out of "use stage in base path" in case people don't want to associate stage information in their swagger file.

To summarize:
- Export should export stage name in the base path, not in the host
- Import should use the stage from the base path, or alternatively from an input parameter if "use stage in base path" is false. 
- Import should exclude the stage element of the base path from the resource paths when creating resources

Sound good?

**Comment by rpgreen** [comment]
Related to https://github.com/awslabs/aws-apigateway-importer/issues/140

**Comment by franksl** [comment]
Sounds absolutely good, either extension or flag are good to me!
Thanks,
Franco

**Comment by mrburrito** [comment]
I've run into the same problem. I borrowed your code a while back to create a Gradle plugin -- currently used internally and not fully tested or supported so I haven't published it -- and was thinking about using the extension property as a solution. I think that is a more portable solution than the command line flags since the Swagger spec will be fully valid and the stage stripping, which is specific to API Gateway, would be documented as an `x-aws-...` extension in the spec itself.

I lean towards that method as well because it means other tools, such as my Gradle plugin, can leverage the same extensions as this command line tool to accomplish the upload in a consistent manner.

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan
