### ISSUE TITLE
Question: Custom Authorizers

### ISSUE THREAD

**Issue by havenwang** [awslabs/aws-apigateway-swagger-importer#169]
Recently, custom authorizers for API Gateway have been announced. Is there a way to include a custom authorizer in Swagger under `x-amazon-apigateway-auth`? 

I've dug around a bit and have not found anything and may have missed it but would like to confirm.

**Comment by MikeD-AWS** [comment]
We are working on adding custom authorizer support for Swagger import and export, but this has not been released yet.

**Comment by cosmincatalin** [comment]
+1 Automatic deployments are difficult without this feature.

**Comment by fdragu** [comment]
Any news on this? if not are you guys willing to accept a pull request with a proposed code change?

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan

**Comment by cosmincatalin** [comment]
The new functionality from the AWS CLI is half-baked. Exporting an API with custom authorizer and trying to create a new API from the fresh export will fail.

**Comment by jackrk** [comment]
Could you provide an example?

**Comment by cosmincatalin** [comment]
@jackrk I'll try to make a sample when I get to work tomorrow.

**Comment by jackrk** [comment]
I may know what the problem is. You have to explicitly request the authorizer extensions 

The import fails because the export without authorizer extensions contains security definitions that are referenced by methods, but are incomplete (no authorizer extension). This is by design to prevent accidentally deploying an open API that you think is authorized. 

Did you get an error like this?

```
Errors found during import:
    Unable to put method 'GET' on resource at path '/': Invalid authorizer id specified. Setting the authorization type to CUSTOM requires a valid authorizer.
Additionally, these warnings were found:
    Unable to create authorizer from security definition: 'test-authorizer'. Extension x-amazon-apigateway-authorizer is required. Any methods with security: 'test-authorizer' will not be created. If this security definition is not a custom authorizer, remove the x-amazon-apigateway-authtype extension and it will be ignored.
```

The authorizer extension is documented here (missing from public docs right now) https://github.com/awslabs/aws-apigateway-importer/issues/187#issuecomment-206475788

If you use the CLI command below you should get authorizer extensions in the export.

```
aws apigateway get-export --parameters '{"extensions":"integrations,authorizers"}' --rest-api-id a1b2c3d4e5 --stage-name dev --export-type swagger /path/to/filename.json
```

**Comment by cosmincatalin** [comment]
That's exactly the problem that I was having. I'll give your solution a try.

Edit:

I can confirm that this works. Thank you for your support.

Best regards,
Cosmin

**Comment by yegor86** [comment]
Hello @jackrk,
Importing Swagger file from _AWS Console UI_ does not create a custom authorizer for me. 

When I import a new swagger file and navigate to a _Method_, which is associated with my custom authorizer, I can find _Auth=CUSTOM_ under _Method Request_ box. However, when I drill down to the method details I see _Authorization = INVALID_ under the  _Authorization Settings_ section 
When I go to _Custom Authorizers_ panel on the left sidebar, I cannot find my new custom authorizer

Importing with _aws-apigateway-importer_ does not work either. Moreover  _aws-apigateway-importer_ does not make any validations against swagger files

**Comment by cosmincatalin** [comment]
Hi @yegor86 , I think the `put-rest-api` functionality is broken. The `import-rest-api` correctly maps the custom authorizer.

**Comment by jackrk** [comment]
Yeah there is but in put-rest-api now, it will generate a bad reference to the authorizer on any existing methods/authorizers (new authorizers work fine). 

Fix is coming out ASAP. You can fix your API in this state by simply correcting the reference in the console, or using the CLI like so:

```
aws apigateway get-authorizers --rest-api-id a1b2c3d4e5
```

(find the correct authorizer and record the ID)

```
aws apigateway update-method --rest-api-id a1b2c3d4e5 --resource-id a1b2c3 --http-method GET --patch-operations "[{\"op\":\"replace\",\"path\":\"/authorizerId\",\"value\":\"AUTHORIZER_ID\"}]"
```
