### ISSUE TITLE
doesn't skip fields starting with "x-"

### ISSUE THREAD

**Issue by benkehoe** [awslabs/aws-apigateway-swagger-importer#172]
Any object in a swagger file can contain fields starting with "x-" for the purpose of extensions; "x-amazon-apigateway-integration" being a prime example. However, the importer doesn't ignore fields starting with "x-" when parsing the file. For example, putting an extension in the "responses" object causes an error, because the importer tries to make an integration with it, but it's not a valid status code.

**Comment by lorenzoaws** [comment]
Thanks for the feedback, we will prioritize accordingly.

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan
