### ISSUE TITLE
Support HEAD methods via swagger file

### ISSUE THREAD

**Issue by rgubby** [awslabs/aws-apigateway-swagger-importer#176]
You can add HEAD methods via the API Gateway console, but if you define a head request in a swagger file, it does not import.

If the head method is the only option, you get an error:

```
com.amazonaws.services.apigateway.model.BadRequestException: The REST API doesn't contain any methods (Service: null; Status Code: 400; Error Code: null;
```

**Comment by kahouieong** [comment]
The swagger parser is using by the API importer doesn't support **HEAD** method.
I will add an item on our backlog to fix this.
As workaround, you can try to update the API importer to use the newer version of swagger parser, and add **HEAD** method in this file [link](https://github.com/awslabs/aws-apigateway-importer/blob/master/src/com/amazonaws/service/apigateway/importer/impl/sdk/ApiGatewaySdkSwaggerApiImporter.java#L193)

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan
