### ISSUE TITLE
Offer a command for validating Swagger file

### ISSUE THREAD

**Issue by henrinormak** [awslabs/aws-apigateway-swagger-importer#180]
Validating a Swagger definition against the Swagger spec is trivial and there are tools for it, however, there are often problems in the custom part used by API Gateway (`x-amazon-apigateway-integration` key), for example problems with mapping or parameters. The importer should offer a command for validating the Swagger definition statically and without automatically also updating/deploying to API Gateway.

The signature could utilise an option to signify that the goal is to just validate the Swagger file, rather than update/create a gateway:

``` sh
./aws-api-import.sh --validate path/to/swagger.yaml
./aws-api-import.sh --validate --raml-config path/to/config.json path/to/api.raml
```

**Comment by henrinormak** [comment]
As a side note, is there any concrete documentation for the `x-amazon-apigateway-integration` key, it's properties and the possible values those can have? If there was a spec, one could at least aim to write their own validator, although documenting dependencies between keys might be tricky (while also being THE biggest reason for this issue).

By dependencies/relationships, I mean requirements similar to the one I've encountered recently:
If you have a `requestParameters` key that maps a request header to an integration header, that request header also has to be defined as part of the `parameters` of the endpoint.

**Comment by rpgreen** [comment]
There is a basic "--test" parameter which will run through the import process and rollback any changes, which is essentially what you are looking for. API Gateway validation logic is complex and managed on the server side, so it would be pointless to attempt to emulate the validation on the cilent side.

We are looking to improve the documentation - the best we have right now is http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions.html

**Comment by henrinormak** [comment]
Just to clarify, the `--test` option would also work for a non-existing API Gateway instance? So basically, would it support the following use case that I am trying to solve:
1. Validate API Swagger via `--test`
2. Deploy some resources to back the API (in my case the Lambda functions etc.)
3. Update and deploy the API (which may or may not already exist).

EDIT: Thanks for responding this fast, and that link is also very useful! :+1:

**Comment by rpgreen** [comment]
Yeah that should work
