### ISSUE TITLE
Allow YAML node anchors on swagger.yaml

### ISSUE THREAD

**Issue by zanona** [awslabs/aws-apigateway-swagger-importer#181]
At the moment it seems that when using [YAML Node Anchors](http://yaml.org/spec/1.2/spec.html#id2785586) causes the importer to crash.

The example bellow would still be valid:

``` yaml
swagger: '2.0'
info:
  version: '0.1.0'
  title: Swagger API
x-amazon-apigateway-integration: &aws-integration
  type: aws
  uri: '...'
  httpMethod: POST
  responses:
    default: { statusCode: '200' }
paths:
  /user:
    post:
      responses:
        200:  { description: '200 OK' }
      x-amazon-apigateway-integration: *aws-integration #<= alias to aws-integration anchor
```

**Comment by kahouieong** [comment]
The swagger parser that API Gateway importer is using doesn't support YAML node anchors.
https://github.com/swagger-api/swagger-parser/issues/146

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan
