### ISSUE TITLE
How to generate the Aws API Extension in Swagger json

### ISSUE THREAD

**Issue by lazygarage** [awslabs/aws-apigateway-swagger-importer#182]
Hi,
I have a query regarding the [apigateway.json](https://github.com/awslabs/aws-apigateway-importer/blob/master/tst/resources/swagger/apigateway.json) in the **tst** resources.

The apigateway.json has the api gateway extensions

```
"x-amazon-apigateway-integration" : {
                    "type" : "aws",
                    "uri" : "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:ACCOUNT_ID:function:myFunction/invocations",
                    "httpMethod" : "POST",
                    "credentials" : "arn:aws:iam::ACCOUNT_ID:role/lambda_exec_role",
                    "requestTemplates" : {
                        "application/json" : "json request template 2",
                        "application/xml" : "xml request template 2"
                    },
                    "requestParameters" : {
                        "integration.request.path.integrationPathParam" : "method.request.querystring.latitude",
                        "integration.request.querystring.integrationQueryParam" : "method.request.querystring.longitude"
                    },
```

Was this json generated via Swagger annotations or is it just a sample file created manually ?
My interest is in the **requestTemplates** and **requestParameters** attributes whose values are more than a simple String.

With **@Extenstion/@ExtenstionProperty** annotations in Springfox, I am only able to generate the key:value pair but not the map with multiple name/value.

Would you know how can we achieve this ? I have also asked this question on Springfox issue board and  wondering if you have any insight to this ?

Thanks,
Pawan

**Comment by rpgreen** [comment]
I can't comment on specific integration issues with SpringFox - better to bring that up with the SpringFox team and let us know if there's any way we can help improve the integration.

This is a custom extension defined by API Gateway - it was not generated using Swagger annotations. Please re-open if you have any direct feedback. Thanks
