### ISSUE TITLE
Extension x-amazon-apigateway-authorizer is required

### ISSUE THREAD

**Issue by sylwit** [awslabs/aws-apigateway-swagger-importer#187]
This afternoon, it seems that an upgrade of the console and the swagger importer has been done.

There is now a issue with custom authorizer. They are not imported but no error is thrown

Trying to import the file with the new importer in the console UI returns a

> Unable to create authorizer from security definition: 'JWT_Authorizer'. Extension x-amazon-apigateway-authorizer is required. Any methods with security: 'JWT_Authorizer' will not be created. If this security definition is not a custom authorizer, remove the x-amazon-apigateway-authtype extension and it will be ignored.

Even if you export and reimport the same file, you have this issue

I can't find anything about this extension x-amazon-apigateway-authorizer

**Comment by jackrk** [comment]
Hmm, it's missing from the public docs. We'll update those, thanks for notifying us.  

Here's an example:

``` javascript
"securityDefinitions" : {
    "test-authorizer" : {
      "type" : "apiKey", // required
      "name" : "Auth", // name of the identity source header
      "in" : "header", // must be header
      "x-amazon-apigateway-authtype" : "oauth2", // unused functionally, just for clarity in swagger defs
      "x-amazon-apigateway-authorizer" : { // here is the extension
        "type" : "token", // required
        "authorizerUri" : "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:xxxxxxxxxxxx:function:auth/invocations",
        "authorizerCredentials" : "arn:aws:iam::xxxxxxxxxxxx:role",
        "identityValidationExpression" : "^x-[a-z]+",
        "authorizerResultTtlInSeconds" : 60
      }
    }
  }
```

then on a method to set the authorizer:

``` javascript
"/http" : {
      "get" : {
        "responses" : { },
        "security" : [ {
          "test-authorizer" : [ ]
        } ],
        "x-amazon-apigateway-integration" : {
          "type" : "http",
          "responses" : {
            "default" : {
              "statusCode" : "200"
            }
          },
          "httpMethod" : "GET",
          "uri" : "http://httpbin.org/get"
        }
      }
    }
```

**Comment by sylwit** [comment]
Thank you very much @jackrk

**Comment by jackrk** [comment]
No problem, we'll get the public docs updated ASAP.

**Comment by jackrk** [comment]
And also to your original point, the authorizers aren't exported right now in the console (they can be using the CLI/SDK). So we should allow the console to export them as well.

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan
