### ISSUE TITLE
x-amazon-apigateway-integration doesn't escape querystring parameters

### ISSUE THREAD

**Issue by sylwit** [awslabs/aws-apigateway-swagger-importer#188]
Hi all,

it looks like the mapping of the query string between integration ans method request doesn't escape the value

```
          "requestParameters": {
            "integration.request.querystring.filters": "method.request.querystring.filters"
          },
```

I use this filter param in that way

> /users?filters={"lastname":"Doe"}

This work perfectly on the API using the beanstalk URL but when I try it by the gateway I get a 400 error. Moreover, if I test the method via the console it works perfectly. So the issue must be in the mapping. If I remove the following special chars { : }, it works (well no 400 error)

Thanks to the documentation
http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html#input-variable-reference I found this : If the JSON input contains unescaped characters that cannot be parsed by JavaScript, a 400 response may be returned. Applying $util.escapeJavaScript() function will ensure that the JSON input can be parsed properly.

Any idea would be appreciate.

Thank you

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan
