### ISSUE TITLE
Building from folders with spaces

### ISSUE THREAD

**Issue by saivan** [awslabs/aws-apigateway-swagger-importer#189]
This is probably a strange issue, perhaps if anybody could replicate it, it would be worth fixing.
Im running on mac,

When I run mvn assembly::assembly, if the pwd path has a space in it the build seems to fail.
I can't test if this happens on another machine, but it seems to be a problem here.

**Comment by sylwit** [comment]
May I suggest you to use the docker image to run the importer ?
It would avoid all that kind of troubles

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199)

Thanks,
Ryan

**Comment by saivan** [comment]
Thanks guys, I'll try out the new tools and see how they work out :)
