### ISSUE TITLE
how to set requestTemplates/responseTemplates to object in x-amazon-apigateway-integration

### ISSUE THREAD

**Issue by EricCat** [awslabs/aws-apigateway-swagger-importer#19]
I want to set  `requestTemplates/response`  like  

```
"application/json" : { "$ref": "#/definitions/Error"} 
```

in`x-amazon-apigateway-integration`

currently, I only found it can accept string format, not array or object. any ideas for it?

**Comment by rpgreen** [comment]
requestTemplates and responseTemplates need to be sent as an escaped JSON String. The example above looks more like a json-schema model than a template. Have a look at http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html for some more info on mapping templates
