### ISSUE TITLE
import Swagger failed -   Parameter type formData not supported

### ISSUE THREAD

**Issue by avtaniket** [awslabs/aws-apigateway-swagger-importer#191]
Hello Geeks,

When trying to import swagger 2.0 def, getting below error 

Your API was not imported due to errors in the Swagger file.
    Parameter type formData for parameter additionalMetadata not supported. Ignoring.
    Parameter type formData for parameter file not supported. Ignoring.

Swagger file

```
swagger: "2.0" 
info:
  version: "1.0.0"
  title: AVT Services
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
schemes:
  - http
paths:
  /images:
    x-swagger-router-controller: imageTest
    post:
      tags: ['images']
      description: images resize
      operationId: "uploadFile"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "petId"
        in: "path"
        description: "ID of pet to update"
        required: true
        type: "integer"
        format: "int64"
      - name: "additionalMetadata"
        in: "formData"
        description: "Additional data to pass to server"
        required: false
        type: "string"
      - name: "file"
        in: "formData"
        description: "file to upload"
        required: false
        type: "file"
      responses:
        "200":
          description: Success
    get:
      tags: ['images']
      description: fetches users images
      # used as the method name of the controller
      operationId: getUserImages
      parameters:
        - name: query
          in: query
          description: The image of the user
          required: true
          type: string
      responses:
        "200":
          description: Success
    delete:
      tags: ['images']
      description: delete images
      # used as the method name of the controller
      operationId: deleteS3Files
      parameters:
        - name: query
          in: query
          description: The image of the user
          required: false
          type: string
      responses:
        "200":
          description: Success

```

**Comment by koxon** [comment]
"in" only supports:
- body
- query
- path

On Mon, May 9, 2016 at 10:22 AM, aniket takarkhede <notifications@github.com

> wrote:
> 
> Hello Geeks,
> 
> When trying to import swagger 2.0 def, getting below error
> 
> Your API was not imported due to errors in the Swagger file.
> Parameter type formData for parameter additionalMetadata not supported.
> Ignoring.
> Parameter type formData for parameter file not supported. Ignoring.
> 
> Swagger file
> 
> swagger: "2.0"
> info:
>   version: "1.0.0"
>   title: AVT Services
> 
> # during dev, should point to your local machine
> 
> host: localhost:10010
> 
> # basePath prefixes all resource paths
> 
> basePath: /
> schemes:
> - http
>   paths:
>   /images:
>     x-swagger-router-controller: imageTest
>     post:
>       tags: ['images']
>       description: images resize
>       operationId: "uploadFile"
>       consumes:
>       - "multipart/form-data"
>       produces:
>       - "application/json"
>       parameters:
>       - name: "petId"
>         in: "path"
>         description: "ID of pet to update"
>         required: true
>         type: "integer"
>         format: "int64"
>       - name: "additionalMetadata"
>         in: "formData"
>         description: "Additional data to pass to server"
>         required: false
>         type: "string"
>       - name: "file"
>         in: "formData"
>         description: "file to upload"
>         required: false
>         type: "file"
>       responses:
>         "200":
>           description: Success
>     get:
>       tags: ['images']
>       description: fetches users images
>       # used as the method name of the controller
>       operationId: getUserImages
>       parameters:
>         - name: query
>           in: query
>           description: The image of the user
>           required: true
>           type: string
>       responses:
>         "200":
>           description: Success
>     delete:
>       tags: ['images']
>       description: delete images
>       # used as the method name of the controller
>       operationId: deleteS3Files
>       parameters:
>         - name: query
>           in: query
>           description: The image of the user
>           required: false
>           type: string
>       responses:
>         "200":
>           description: Success
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/awslabs/aws-apigateway-importer/issues/191

## 

Nicolas Menciere
Co-founder and CTO
http://bfansports.com

**Comment by avtaniket** [comment]
If you check swagger 2.0 spec here http://swagger.io/specification/

`in string  Required. The location of the parameter. Possible values are "query", "header", "path", "formData" or "body".`

How to upload file if can't used **formData**, Do you have any swagger sample?

**Comment by SandeshSarfare** [comment]
@rpgreen what can be used instead of formData?

**Comment by kadosh1000** [comment]
I too encountered that problem.
How can I solve that without using formData?

**Comment by nimboya** [comment]
I am encountering thesame problem too. Anyone with a solution please help?

**Comment by avtaniket** [comment]
Hello @nimboya

You can use **S3** to upload file and then pass data to API gateway or integrate **Lambda** to do process upload.

Eg. Check here for [Lambda](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-content-encodings-examples-image-lambda.html)

**Comment by nimboya** [comment]
I have discovered the solution AWS API gateway does not support 'formData' check it here so it is resorting to 'body' that is the solution

https://forums.aws.amazon.com/message.jspa?messageID=723682
