### ISSUE TITLE
Unable to import api definition from aws console?

### ISSUE THREAD

**Issue by SandeshSarfare** [awslabs/aws-apigateway-swagger-importer#194]
Hi,

I have been trying to import my api definition file which is a yaml file but when I import it from console I am getting several errors

`Invalid model name specified: application/json=null`

`Model name must be alphanumeric: inline_response_200_1`

`Invalid model name specified: null`

`Reference to model 'inline_response_200_1' not found. Ignoring.`

How can I get rid of these ?

**Comment by SandeshSarfare** [comment]
I can even post definition of api if need be

**Comment by koxon** [comment]
You should post your file.
Looks like an indentations issue or syntax error.

**Comment by SandeshSarfare** [comment]
Here it is
Please try it through console and let me know if I am doing anything wrong

[swaggerYAML.txt](https://github.com/awslabs/aws-apigateway-importer/files/286379/swaggerYAML.txt)

**Comment by koxon** [comment]
Have you validated your file in swagger?

**Comment by SandeshSarfare** [comment]
Yes I did on http://editor.swagger.io/#/ but it had one warning 

```
Swagger Warning
Definition is not used: #/definitions/x-any
```

**Comment by SandeshSarfare** [comment]
![image](https://cloud.githubusercontent.com/assets/16500341/15608199/dcc879ae-2435-11e6-9401-5adf8c441960.png)

This is the snapshot

**Comment by SandeshSarfare** [comment]
Did you get a chance to look at it? i am stuck badly here

**Comment by SandeshSarfare** [comment]
I need it to happen by today itself

**Comment by SandeshSarfare** [comment]
@koxon 
I have validated the swagger definition without any errors and warnings but when I do 

`aws apigateway import-rest-api --body D://./swagger.yaml`
or
`aws apigateway import-rest-api --body D://./swagger.json
`
I get error as invalid 

> A client error (BadRequestException) occurred when calling the ImportRestApi operation: Invalid Swagger 2.0 input.

**Comment by koxon** [comment]
I get the same thing when using the api. Not sure why.

Amazon, shouldn't the format be the Same for both api and aws swagger
importer?

**Comment by koxon** [comment]
When I ran Into those issues,  I just added sections to the file,  one
after another to nail the culprit.

**Comment by jackrk** [comment]
Have you tried without the tags? I have a feeling those might be causing the validation error. Even if you remove the tags I still see a lot of things that will give you errors/warnings when you attempt to import it, mainly: 1) model names must be alphanumeric 2) I don't see any API Gateway integrations on the methods, which will prevent you from deploying it

**Comment by SandeshSarfare** [comment]
@jackrk can I share the yaml file with you?

**Comment by SandeshSarfare** [comment]
I have done everything to upload this on AWS console but no luck
[awsSwaggerYaml.txt](https://github.com/awslabs/aws-apigateway-importer/files/294905/awsSwaggerYaml.txt)

You can see aws integration on methods here

**Comment by SandeshSarfare** [comment]
Its been more than a week That I have been doing this and on top of that Its even a valid YAML
@jackrk I even tried removing tags

**Comment by SandeshSarfare** [comment]
@jackrk Now I am getting error as "Invalid swagger definition - request body was empty"
After solving all the errors

**Comment by SandeshSarfare** [comment]
Now I am getting "Parameter type formData for parameter IntPubCenterID not supported. Ignoring." for parameters

**Comment by jackrk** [comment]
First I will point out that API Gateway accepts valid Swagger 2.0 definitions but there are bound to be plenty of errors and warnings depending on things specific to API Gateway. For example we have extra validation on Models, which is what you're seeing in the response. 

If you use the CLI instead of the console, you can set an option to not fail on warnings. The message ""Parameter type formData for parameter IntPubCenterID not supported. Ignoring."" is a warning and you can ignore these if you use the CLI. See http://docs.aws.amazon.com/cli/latest/reference/apigateway/import-rest-api.html

**Comment by SandeshSarfare** [comment]
@jackrk I resolved the issue by using body instead of form-data
