### ISSUE TITLE
Custom Authorizers wont' send CORS headers

### ISSUE THREAD

**Issue by zanona** [awslabs/aws-apigateway-swagger-importer#195]
Hi, I know this repository is about the imported but I didn't know where to post this.
I am trying to use custom authorizers which are all set.

However those won't return necessary CORS headers so we can use through AJAX calls when returning 401 unauthorized responses.

How can we build dynamic apps this way?

**Comment by lorenzoaws** [comment]
You can try posting your question to the official API Gateway forums at https://forums.aws.amazon.com/forum.jspa?forumID=199&start=0

**Comment by zanona** [comment]
thanks for the link Lorenzo I will try it over there.

**Comment by shellandbull** [comment]
Running into this as well...AWS has explicitly identified this as an issue and not been able to provide a fix nor a workaround in +1 year

**Comment by zanona** [comment]
That's is indeed quite frustrating @mariogintili 
Please see:

- http://stackoverflow.com/questions/36913196
- https://forums.aws.amazon.com/thread.jspa?messageID=728839

**Comment by wparad** [comment]
I think this is fixed now, right?
* https://stackoverflow.com/questions/40585016/is-it-possible-to-add-an-http-header-from-aws-custom-auth-on-api-gateway
* http://docs.aws.amazon.com/apigateway/latest/developerguide/use-custom-authorizer.html#api-gateway-custom-authorizer-output

Does that work for CORS?
