### ISSUE TITLE
Feature Request: deployment description (e.g., --deploy-description) to go along with --deploy

### ISSUE THREAD

**Issue by nwightkin** [awslabs/aws-apigateway-swagger-importer#20]
Hello,

First off, great tool! I'm using it as part of CodePipleine to deploy new versions of my API. Any chance you could provide a "deploy description" command line argument to go along with --deploy? That way the deployment within API Gateway will indicate, e.g., a version number, etc.

Thank you!
Nick

**Comment by bholbrook73** [comment]
+1 
This would be a great feature

**Comment by charleswhchan** [comment]
+1
Agree. This would be a good way to attach metadata to a release. 

Currently, AWS console will only show a list of dates time corresponding to each version being deployed. Having a description will allow an easier time of knowing what version a release corresponds to rollback to an earlier version.

**Comment by rdewaele** [comment]
+1
In our deployment flow this is currently the main thorn in the eye - no good way to clearly document why a deployment was done, which is especially interestring in non-development environments.

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan
