### ISSUE TITLE
Root security definition

### ISSUE THREAD

**Issue by pacey** [awslabs/aws-apigateway-swagger-importer#204]
In the Swagger 2.0 spec you can specify a security method that applies to the whole of that API spec (http://swagger.io/specification/#swagger-object-14 security field).

> A declaration of which security schemes are applied for the API as a whole. The list of values describes alternative security schemes that can be used (that is, there is a logical OR between the security requirements). Individual operations can override this definition.

I added this into my swagger file, with the corresponding securityDefinitions config and it was imported without error. However, it didn't actually apply the security to any of my methods. Is this a known issue? Applying it at a per method level seems to work, which is an acceptable workaround.

**Comment by MikeD-AWS** [comment]
API Gateway doesn't support the API level security field.  You have to apply it per method.

**Comment by MikeD-AWS** [comment]
Also, we recommend customers use the integrated import API available in the latest SDK and CLI tools rather than the awslabs/aws-apigateway-importer
