### ISSUE TITLE
What's the relationship between Swagger definition and header returned by Lambda function?

### ISSUE THREAD

**Issue by syang** [awslabs/aws-apigateway-swagger-importer#205]
I have my SAM configuration of a Restful URI (note: this snippet defines the response type as **'text/plain'**)

```
        paths:
          '/questions':         
            get:
              produces:
              - 'text/plain'
              responses:
                '200':
                  description: 'successful'
                  schema:
                    type: number
                  .....
 
```

And in the lambda function that processing  the GET method of /questions, I accidentally returned **application/jso**n, as show below

```
const createResponseWithHeader = (statusCode, body) => {
  console.log("inside createResponseWithHeader, body = ", body);
  let headerString = {
    "Content-Type": 'application/json',
    "Access-Control-Allow-Origin": '*'
  };
  return {
    statusCode: statusCode,
    headers: headerString,
    body: body
  }
};
```
Apparently, the above lambda function did not comply the definition of the Swagger definition, but I realized that the API-Gateway did not report any error or warning.

How should I understand the above case? (should I believe that Swagger's definition is only for documentation purpose but has not run time checking role?)

**Comment by lorenzoaws** [comment]
You're correct. API Gateway does not currently enforce the "produces" attribute in Swagger, it should only be used for documentation purposes.

**Comment by syang** [comment]
@lorenzoaws thanks for the clarification -- and it's helpful for us to understand the under the hood mechanism. I am closing this now.
