### ISSUE TITLE
Feature Request: use EC2 Role temp credentials

### ISSUE THREAD

**Issue by nwightkin** [awslabs/aws-apigateway-swagger-importer#21]
Hello,

I'm attempting to use the importer as part of a continuous delivery pipeline (using AWS CodePipeline). As part of this pipeline I'm running the importer from an EC2 instance with an EC2 Role policy to grant write permissions to API Gateway. But the importer is exiting with error because I don't think it can get temp credentials for an EC2 role. The error tells me to use "aws configure". As a stopgap I've created an IAM user for this importer to use, but I'd like to leverage roles and not have credentials on the instance. Is this currently possible? If not, could you please add this feature to your backlog?

Thank you!
Nick

**Comment by rpgreen** [comment]
Hi Nick,

EC2 instance role credentials are not currently supported by the tool. You are correct in that you would have to set user credentials using 'aws configure'. I will keep this in the backlog.

In the meantime, it would be trivial to modify ApiImporterModule.provideCredentialsProvider() to return a new InstanceProfileCredentialsProvider. Let me know if this works and feel free to send a pull request

**Comment by nonspecialist** [comment]
I'd just like to +1 this -- except for the case of Federated Identites. We don't allow people to create IAM users, because persistent credentials have a habit of leaking, and are really annoying to maintain when you use multiple accounts.

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan
