### ISSUE TITLE
Provide Some Basic Examples

### ISSUE THREAD

**Issue by austencollins** [awslabs/aws-apigateway-swagger-importer#3]
I'm referencing the README and  [this deleted file](https://github.com/awslabs/aws-apigateway-swagger-importer/commit/8647589cb64bbfba807ef471e82674cf1a67fdb3) for examples on how to include the Swagger API Gateway Extension for each method.

Could you gents throw together a few more examples?  I'm currently looking for examples on:
- How request and response templates are included
- How to specify no "Auth" on my method
- I've hooked up a method to use a lambda via this `uri`, but it registers the `Integration Type` as a AWS Service Proxy, instead of Lambda Function.  How can I modify this `uri` to set the `Integration Type` as a Lambda function:  arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:871893991718:function:users_show

**Comment by rpgreen** [comment]
I would encourage you to check out the [API Reference](http://docs.aws.amazon.com/apigateway/api-reference) and the service documentation to get up to speed on any API Gateway-specific concepts.

To specify "no auth" for a method, simply remove x-amazon-apigateway-auth or set its type to "none".

To wire up a lambda function invocation, set the your integration like this:

```
...
  "type" : "aws",
   "uri" : "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:871893991718:function:users_show/invocations",
  "httpMethod" : "POST",
...
```

In the meantime, we will work on writing some documentation for our extensions.
