### ISSUE TITLE
General Problems

### ISSUE THREAD

**Issue by midwire** [awslabs/aws-apigateway-swagger-importer#35]
We are excited to be able to use this tool. We are hoping it will allow us to make modifications quickly and re-deploy where using the API Gateway GUI requires deleting and adding entire resources and method chains.

After testing for hours and reading all of the issues, I am unable to figure out why:
- It raises an exception every time we try to use a JSON swagger definition. (YAML works fine)
- After converting the sample JSON files to YAML (in `./tst/resources`) and successfully importing some of those, when trying to test some methods using the API Gateway GUI, we discover only the method verbs are imported. We click on the verb to see that the endpoints, parameters, etc are missing, but ready to fill out using the GUI. In addition when we click on a resource/path the `waiting` icon spins forever in the right side pane.

I feel fairly certain we are missing something as nobody else has reported issues like these. Please advise.

Example of the persistent JSON import errors:

```
; line: 12, column: 4]
2015-09-11 10:24:02,266 ERROR - Error importing API from Swagger
java.lang.NullPointerException
    at com.amazonaws.service.apigateway.importer.impl.sdk.ApiGatewaySdkSwaggerApiImporter.updateApi(ApiGatewaySdkSwaggerApiImporter.java:109)
    at com.amazonaws.service.apigateway.importer.impl.ApiGatewaySwaggerFileImporter.updateApi(ApiGatewaySwaggerFileImporter.java:58)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.execute(ApiImporterMain.java:107)
    at com.amazonaws.service.apigateway.importer.ApiImporterMain.main(ApiImporterMain.java:65)
```

Example of missing methods in the GUI:

![api_gateway](https://cloud.githubusercontent.com/assets/178386/9818899/65887b0a-5870-11e5-8819-cf69f754f1d2.png)

Swagger Test File (YML format):

```
swagger: '2.0'
info:
  title: RFS Swagger API
  description: Rallyhood File Service API
  version: 1.0.0
host: 4fca387b.ngrok.io
schemes:
  - http
  - https
basePath: /{version}
consumes:
  - application/json
produces:
  - application/json
paths:
  '/folders':
    get:
      summary: Folder Data
      description: |
        The Folder endpoint returns data for all Folder resources.
        Parameters may be passed to filter the response.
      parameters:
        - name: page
          in: query
          description: Return given page of results
          default: 1
          required: false
          type: integer
        - name: per_page
          in: query
          description: Return per_page count of Folders for each given page
          default: 20
          required: false
          type: integer
      tags:
        - Folders
      responses:
        '200':
          description: Folder Array
          schema:
            title: Folders
            type: array
            items:
              $ref: '#/definitions/Folder'
  '/{id}':
    get:
      parameters:
        - name: id
          in: path
          description: ID of the folder
          required: true
          type: integer
      responses:
        '200':
          description: Returns the selected Folder
          schema:
            type: object
            properties:
              data:
                $ref: '#/definitions/Folder'

definitions:
  Folder:
    type: object
    description: Folder Resource
    properties:
      id:
        type: number
        description: ID of the resource
      name:
        type: string
        description: 'Display name of the Folder.'
      user_id:
        type: number
        description: ID of the user to which the folder belongs.
      folderable_id:
        type: number
        description: ID of the Rally or Corp to which the folder belongs.
      folderable_type:
        type: string
        description: Type of object this folder belongs to.
      folder_id:
        type: number
        description: ID of the parent folder. May be blank or null.
      updated_at:
        type: string
        description: Date last updated
      created_at:
        type: string
        description: Date created
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
```

**Comment by midwire** [comment]
Resource path spins forever when selected...

![api_gateway](https://cloud.githubusercontent.com/assets/178386/9818983/e3a85ee2-5870-11e5-8d9c-31e2f50e10b0.png)

**Comment by eyston** [comment]
You are defining your API but not the integration part.  When you go to the console it is going to prompt you to finish the configuration.

The spinner spinning forever is a bug I'm pretty sure.  I _think_ if you specify an integration type it fixes this.  It definitely is fixed if you define an integration type as well as configure the response.

Here is a simple example (in JSON):

``` json
{
  "swagger": "2.0",
  "info": {
    "title": "Scratch"
  },
  "paths": {
    "/orgs": {
      "get": {
        "responses": {
          "200": {}
        },
        "x-amazon-apigateway-integration": {
          "type": "http",
          "uri": "https://api.github.com/orgs/facebook",
          "httpMethod": "GET",
          "responses": {
            "default": {
              "statusCode": "200"
            }
          }
        }
      }
    }
  }
}
```

I don't know swagger -- I just did the bare minimum to make this tool work.  I'm fairly sure this is the minimal you need to setup a working HTTP integration.

Things of interest:
- `x-amazon-apigateway-integration` holds all the parts for integrations.
- `type` can be `http`, `aws`, etc.  `mock` is broken on master (going to put a bug in on that)
- for `http`, `uri` / `httpMethod` describe your integration request. (I'm just starting with lambdas so don't know how to do them yet).
- `responses` is a key/value map -- "default" is a catch all but you can do static values / regular expressions to match just like you could in the console.  You then set which `statusCode` this integration response maps to.

I've been using this for reference:

https://github.com/awslabs/aws-apigateway-swagger-importer/blob/master/tst/resources/apigateway.json

**Comment by midwire** [comment]
That certainly gets us closer. Thank you! It would be ideal if we could export the JSON from the web console and then modify. Hopefully, with trial and error, I can get the JSON/YML correct.

Now getting:

```
2015-09-11 13:18:25,730 ERROR - Error importing API from Swagger
com.amazonaws.services.apigateway.model.BadRequestException: Invalid mapping expression specified: Validation Result: warnings : [], errors : [Invalid mapping expression specified: method.response.querystring.page] (Service: null; Status Code: 400; Error Code: null; Request ID: 7e6593b0-58b1-11e5-8606-b5053a2b46ce)
```

Which says `responseParameters:` are not mapped properly. In particular for my `page` parameter. I'll play around with it. 

Thanks again!

**Comment by eyston** [comment]
`method.response.querystring.page` would I think be `method.request.querystring.page` (not `response`).

e.g.

``` json
"requestParameters": {
  "integration.request.querystring.page": "method.request.querystring.page"
}
```

... but just a guess!

And yes, trial and error has been my way too.  I just keep running `--update --deploy` whenever I make an edit to see what happens!

**Comment by midwire** [comment]
Good catch! It is working now. Thanks again @eyston !
