### ISSUE TITLE
IntegrationType mock is not supported

### ISSUE THREAD

**Issue by eyston** [awslabs/aws-apigateway-swagger-importer#36]
Hello,

When setting a type of `mock` an exception is thrown.  The cause is this line:

https://github.com/awslabs/aws-apigateway-swagger-importer/blob/master/src/com/amazonaws/service/apigateway/importer/impl/sdk/ApiGatewaySdkSwaggerApiImporter.java#L417

It does a `toUpperCase` on the `type`.  Unfortunately `Mock` is not all uppercase:

https://github.com/awslabs/aws-apigateway-sdk-java/blob/master/src/main/java/com/amazonaws/services/apigateway/model/IntegrationType.java#L25

Thanks!

**Comment by rpgreen** [comment]
Thanks for reporting. This is a bug in the SDK. Will follow up

**Comment by rpgreen** [comment]
This should be fixed now. Please update and rebuild
