### ISSUE TITLE
how can i set a request model?

### ISSUE THREAD

**Issue by giowe** [awslabs/aws-apigateway-swagger-importer#42]
hi, i have to set a request model for the application/json request but i can't figure out where i can set it in the apigateway-integration...

"x-amazon-apigateway-integration": {
                    "type": "aws",
                    "uri": "arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:477398036046:function:debug/invocations",
                    "httpMethod": "POST",
                    "credentials": "arn:aws:iam::477398036046:role/lambda_exec_role",
                    "requestTemplates": {
                        "application/json": ""
                    },
                    "requestParameters": {
                        "integration.request.path.alias": "method.request.path.alias"
                    },
                    "responses": {
                        "2//d{2}": {
                            "statusCode": "200"
                        },
                        "default": {
                            "statusCode": "400"
                        }
                    }
                }

**Comment by rpgreen** [comment]
This goes in the standard Swagger "Operation" section.

Request models go in "parameters" and response models go in responses. i.e.

```
 "parameters": [
          {
            "name": "pet",
            "in": "body",
            "description": "Pet to add to the store",
            "required": true,
            "schema": {
              "$ref": "#/definitions/NewPet"
            }
          }
```

The model schema itself goes in the "definitions" section. Have a look at the Swagger spec for more details.
