### ISSUE TITLE
Using external references in model definition

### ISSUE THREAD

**Issue by AndreyStrib** [awslabs/aws-apigateway-swagger-importer#43]
Using external references in a way suggested in aws forum (https://forums.aws.amazon.com/thread.jspa?threadID=214765&tstart=0) like ("$ref": "https://apigateway.amazonaws.com/restapis/API_ID/models/MODEL_NAME") in Swagger file is imported to Gateway API in inlined form like that:

```
{"type":"object","properties":{"name":{"type":"string"},"card":{"$ref":"#/definitions/Card"}},"definitions":{"Card":{"type":"object","properties":{"last4":{"type":"string"}}}}}
```

Is it possible to preserve external reference in form it was declared in swagger template?

Original model definitions in swagger:

```
"User": {
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "card" : {
        "$ref": "https://apigateway.amazonaws.com/restapis/r8i8miwg18/models/Card"
    }
  }
},
"Card": {
  "type": "object",
  "properties": {
    "last4": {
      "type": "string"
    }
  }
}
```

**Comment by rpgreen** [comment]
We can definitely look into it. Just curious - why do you need them to be imported in canonical-reference form?

**Comment by AndreyStrib** [comment]
I have Card model referenced in multiple models throughout API. 
If it is imported in inlined form to aws gateway, resulting IOS SDK will contain different classes for each inlined Card model.
For example, Card model is used inside User model and inside Account model. In that case sdk will contain two different classes with the same content: User_card, Account_card.
In case we will be able to have swagger file imported in form of external reference, than it will lead to single Card class, reused throughout API (in our example, Card class will be used as in User as in Account class).
I hope my explanation makes sense. Let me know if more clarifications are needed

**Comment by rpgreen** [comment]
That makes sense. Have you tested that the iOS SDK generates the correct classes if you manually create models with external references?

**Comment by AndreyStrib** [comment]
Yes, I tested. It generates classes which are reusable throughout api.
Although in both cases of inlined or external references, there is currently bug in ios sdk generator, I described in this issue: 
https://forums.aws.amazon.com/thread.jspa?threadID=216636&tstart=0
AWS guys promised to look at it shortly, I hope it will be fixed soon.

**Comment by rpgreen** [comment]
We do have a fix for that issue coming out soon. It may be a bit longer to address the external reference issue. If you can get it working in the short-term please feel free to send a pull request.

**Comment by AndreyStrib** [comment]
I've updated importer in a separate fork to replace all $ref in models with pattern "https://apigateway.amazonaws.com/restapis/{API_ID}/models/{ModelName}".
It does what I need. But model refs inlining is thrown away.
Not sure whether such referencing suites all cases. Are there cases where inlining is preferable? 
Let me know if you want this to be sent in pull request.

**Comment by arabold** [comment]
Here's a +1 on this. Just ran into exactly the same problem with models being inlined and thus bloating the SDK with duplicate classes unnecessarily. External references would be exactly what I need.

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan
