### ISSUE TITLE
Region not read correctly from .aws/config file (NullPointer Exception)

### ISSUE THREAD

**Issue by mpuittinen** [awslabs/aws-apigateway-swagger-importer#45]
region:eu-west-1 is read as -west-1 in AwsConfig.java
There is a wrong offset of 9 characters for reading the region info. Should be 7.
This caused a NullPointer Exception being thrown when creating APIs

**Comment by rpgreen** [comment]
Which version of the AWS CLI are you using? Can you show me the contents of ~/.aws/config

**Comment by AndreyStrib** [comment]
Confirm the issue. mpuittinen's fix helps.
