### ISSUE TITLE
How to get identifier of imported API?

### ISSUE THREAD

**Issue by AndreyStrib** [awslabs/aws-apigateway-swagger-importer#47]
How can I get identitfier of API created by importer, in a way that can be reused by following update/deploy commands?
Is it possible to update aws-api-import to return the identifier?

**Comment by rpgreen** [comment]
Curious, why do you need to update after creating it? There is a
deploy flag to create/deploy or update/deploy.

On Monday, 28 September 2015, AndreyStrib notifications@github.com wrote:

> How can I get identitfier of API created by importer, in a way that can be
> reused by following update/deploy commands?
> Is it possible to update aws-api-import to return the identifier?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/awslabs/aws-apigateway-swagger-importer/issues/47.

##

**Comment by AndreyStrib** [comment]
In my project api gateway is built around lambdas. I've made few scripts that simplify developing/deployment and defining inputs and outputs of lambdas, also I've automated api swagger file generation based on lambdas in my project, which is used by another script to update api in aws, using importer. To make this update without necessity to provide api id manually, I  need to get api id from importer on api creation.
Currently, in my fork I changed importer to output api id and than script tries to catch it.

**Comment by cosbor11** [comment]
I also need this functionality to automate the gateway creation since there is no cloudformation solution available. Each time I run the importer a new API is created. I would like to update any existing APIs that have the same name (If one does not exist, create it). 

Is this possible with this importer?

**Comment by Nr18** [comment]
You could use the CLI tool for that:

```
aws apigateway get-rest-apis --query 'items[?name == `API_NAME`] | [0].{id: id}'
```

if the value is null create else update the returned id

**Comment by cosbor11** [comment]
Thanks that's very helpful. Where is the --query syntax documentation?

Im trying to get the id string from the json 

```
{
    "id": "cdw66dzmk7"
}
```

**Comment by cosbor11** [comment]
I figured it out: 

```
  --output text 
```

**Comment by Nr18** [comment]
If you have jq available you could use the following as well:

```
aws apigateway get-rest-apis --query 'items[?name == `API_NAME`] | [0].{id: id}' --output json | jq -r '.id'
```

Could come in handy in some situations.

The --query syntax is JMESPath, see http://jmespath.org

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan
