### ISSUE TITLE
[Question] How do you map response codes?

### ISSUE THREAD

**Issue by AaronRustad** [awslabs/aws-apigateway-swagger-importer#48]
I hope I'm not out of line asking this question here, but since swagger-importer sits nicely between the technologies at hand, I'm hoping someone here may be able to help out.

How does one map the the response codes appropriately between an API defined in Swagger and AAG?  I've seen that we can do regex matching to have all 500 level codes mapped to a single 500 error code. And that might be fine for server side errors, but when we talk about client side errors (the 400s), it seems to me that any number of responses are possible, and it doesn't make sense to map 4XX => 400.

So, I wrote code to manually map app the responses from my API to match those available in AAG. As you can imagine, the resulting Swagger file is huge and Swagger-UI lists every single response code even though it's not _really_ needed (see image below).

![swagger_ui](https://cloud.githubusercontent.com/assets/17159/10175509/7dee72a4-66ac-11e5-846f-3985dde99cb3.jpg)

Now, of course, if I omit the definition of the response code, AAG will error out because it doesn't understand what it should do with the response code.

I feel like I'm doing something wrong here, but I don't see any other way. What are others doing.. surely I can't be the only one experiencing this.

Thanks so much for your help.
Aaron.

**Comment by nguyenquynhan** [comment]
I get same issue . Please more detail for document tools

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan
