### ISSUE TITLE
Spaces around = in config causes regex to fail

### ISSUE THREAD

**Issue by dave-kennedy** [awslabs/aws-apigateway-swagger-importer#52]
`aws configure` adds spaces around = in the config file, e.g.:

```
[default]
output = json
region = us-west-2
```

(I wonder if this is just on Windows?)

Anyhoo cb1bf6e broke this. Will submit a patch.

**Comment by rpgreen** [comment]
This was broken by a recent pull request. I had a look over and it looked like the new code would support both "region = us-west-2" and "region=us-west-2", but perhaps not. I'll keep an eye out for the patch

**Comment by dave-kennedy** [comment]
Ok, it might take a little while. Still new to Java :)

Edit: nevermind, that wasn't bad at all!
