### ISSUE TITLE
How to specify http proxy for an endpoint?

### ISSUE THREAD

**Issue by dwery** [awslabs/aws-apigateway-swagger-importer#55]

**Comment by rpgreen** [comment]
Can you provide some more information on what you're trying to do?

**Comment by dwery** [comment]
I would like to set the HTTP proxy, as in AWS's console

Method Executuion -> Integration Request -> Integration type -> HTTP Proxy
(and also endpoint URL)

**Comment by rpgreen** [comment]
Simply use http for integration type and the url field. See https://github.com/awslabs/aws-apigateway-importer/blob/master/tst/resources/swagger/apigateway.json#L187

**Comment by dwery** [comment]
thank you very much!
