### ISSUE TITLE
[Feature Request] Run aws-apigateway-importer via AWS Lambda

### ISSUE THREAD

**Issue by jason-riddle** [awslabs/aws-apigateway-swagger-importer#57]
Since this is just written in Java, would it be possible to run this via AWS Lambda? So for example, you could have a lambda function that creates a new api gateway and another that updates the api gateway?

**Comment by rpgreen** [comment]
Very cool idea! It should be pretty simple to write an lambda entry point to hook into the ApiImporter classes. You could pull the Swagger file from S3 or wherever, and then read it from /tmp

**Comment by austencollins** [comment]
:+1: We'll build this soon!

**Comment by BryanCrotaz** [comment]
I'm already doing it - just wrap a node.js lambda around the shell script

**Comment by petemounce** [comment]
Very interested in this - #141 was my version of the same question. I'd love to just push a swagger definition to somewhere in S3, and have lambda be told about that via an event notification to then go and update my API.

**Comment by BryanCrotaz** [comment]
Check out https://github.com/carlnordenfelt/aws-api-gateway-for-cloudformation

We compile our swagger to a CF template then use the above. So much
more reliable than the Java

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan

**Comment by BryanCrotaz** [comment]
Can we import using Cloud Formation? The reason we are using this library
is to make a Lambda-backed Custom Resource

On 6 April 2016 at 19:20, Ryan Green notifications@github.com wrote:

> Closed #57 https://github.com/awslabs/aws-apigateway-importer/issues/57.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/awslabs/aws-apigateway-importer/issues/57#event-617245192

## 

Bryan Crotaz
Managing Director
Silver Curve
