### ISSUE TITLE
sig mismatch error when query string val contains escape chars

### ISSUE THREAD

**Issue by doapp-ryanp** [awslabs/aws-apigateway-swagger-importer#60]
I have a config that looks like this:

```
{
...
      "RequestTemplates": {
        "application/json": "{\"query\":\"$util.urlDecode($input.params('q'))\"}"
      },
      "RequestParameters": {
        "integration.request.querystring.integrationQueryParam": "method.request.querystring.q"
      },
...
}
```

And it works fine when I pass a query string value (to `q`) without escape chars.  However when my query string param has escape chars, like space (hi%20there) I get a sig mismatch error from the API Gateway.

Here is full example via the tester:
![screen shot 2015-10-19 at 2 52 21 pm 1](https://cloud.githubusercontent.com/assets/1036546/10620816/cf6cd75a-7742-11e5-913c-75fb99512c62.png)

When I then delete the query string and change the integration request to mock and back via the web UI, then re-create the query string and integration request via the web UI the query string param with escape chars works just fine.

I think it has something to do with the string `integrationQueryParam` making it into the `Query Strings` section of the Integration request:
![image](https://cloud.githubusercontent.com/assets/1036546/10620963/757855f2-7743-11e5-94e8-b21b0efb3a78.png)

I can't figure out how that gets there - and when I remove the query string `q` from the method request in the UI, the `integrationQueryParam` is still in the `Query Strings` section of the Integration request.  The only way I can get rid of it is to convert the Integration request into a  mock then move it back to my lambda.

any ideas?

**Comment by austencollins** [comment]
:+1:

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan
