### ISSUE TITLE
Determining API ID

### ISSUE THREAD

**Issue by lashex** [awslabs/aws-apigateway-swagger-importer#62]
As a n00b to this importer it would be nice if the README documented how one can actually determine the API ID that is supposed to be used in the `--update` command.

**Comment by koxon** [comment]
+1

I figure the console url would contain it but this was not obvious
ᐧ

On Wed, Oct 21, 2015 at 1:29 PM, Brett Francis notifications@github.com
wrote:

> As a n00b to this importer it would be nice if the README documented how
> one can actually determine the API ID that is supposed to be used in the
> --update command.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/awslabs/aws-apigateway-importer/issues/62.

## 

Nicolas Menciere
Co-Founder and CTO
Sport Archive Inc.

**Comment by rpgreen** [comment]
The API ID is logged in the output of the create command. You can also see it in the URL of the console, or of the subdomain of the deployed API. Linking this to #30 documentation issue
