### ISSUE TITLE
Errors: build tests, and first run

### ISSUE THREAD

**Issue by FrancescoRizzi** [awslabs/aws-apigateway-swagger-importer#68]
Hello. First time user here (I'm on Windows). Got AWS CLI in place though.

_Update:_ It seems the `Build with mvn assembly:assembly` step fails if your current working path includes spaces (eg: C:\Users\frankr\Documents\Folder With Spaces\aws-importer ). Some step in the sequence should probably add quotes around paths to avoid this. 

What follows is my original report, for reference.
- `Build with mvn assembly:assembly`: all right, so I got Maven (and Java), but when I do this it ends with 4 errors among the tests:

>  testImport_create_resources(com.amazonaws.service.apigateway.importer.impl.Api
> GatewayRamlFileImporterTest): C:\Users\frankr\Documents__AWSSS__\Amazon%20API%2
> 0Gateway%20Importer\aws-apigateway-importer-master\build\private\classes\tests\r
> aml\apigateway.json (The system cannot find the path specified)
> 
> testImport_create_api(com.amazonaws.service.apigateway.importer.impl.ApiGatewa
> yRamlFileImporterTest): C:\Users\frankr\Documents__AWSSS__\Amazon%20API%20Gatew
> ay%20Importer\aws-apigateway-importer-master\build\private\classes\tests\raml\ap
> igateway.json (The system cannot find the path specified)
> 
> testImport_create_models(com.amazonaws.service.apigateway.importer.impl.ApiGat
> ewayRamlFileImporterTest): C:\Users\frankr\Documents__AWSSS__\Amazon%20API%20Ga
> teway%20Importer\aws-apigateway-importer-master\build\private\classes\tests\raml
> \apigateway.json (The system cannot find the path specified)
> 
> testImport_create_methods(com.amazonaws.service.apigateway.importer.impl.ApiGa
> tewayRamlFileImporterTest): C:\Users\frankr\Documents__AWSSS__\Amazon%20API%20G
> ateway%20Importer\aws-apigateway-importer-master\build\private\classes\tests\ram
> l\apigateway.json (The system cannot find the path specified)
> 
> Tests run: 21, Failures: 0, Errors: 4, Skipped: 1

Could this be due to spaces in my path (note the "Amazon API Gateway Importer" dir that has been treated into "Amazon%20API%20Gateway%20Importer") ?
- Assuming for a minute the errors were minor, I went ahead, got a simple swagger.json file, placed it in the importer's top directory (so it's a sibling of README.md) and:
  
  aws-api-import.cmd --create ./swagger.json

But that generated an error:

> $>java -jar build/maven/aws-apigateway-swagger-importer-1.0.1-jar-with-dependencies.jar --create ./swagger.json
> Error: Unable to access jarfile build/maven/aws-apigateway-swagger-importer-1.0.
> 1-jar-with-dependencies.jar

Could this be due to the error during the build?

Thanks in advance.

**Comment by lauralesteves** [comment]
I've successfully builded but I have the same problem described above :/

Any ideias?

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan

**Comment by SandeshSarfare** [comment]
I am not able to import it even using aws console 
Issue is open at
https://github.com/awslabs/aws-apigateway-importer/issues/194
