### ISSUE TITLE
Response regex requires '\' to be escaped

### ISSUE THREAD

**Issue by thedevkit** [awslabs/aws-apigateway-swagger-importer#70]
This just started happening recently (probably in the same update as #69). If I have a response regex such as the following: `"INT(.|\n)*"`

What actually gets imported to API Gateway is: `"INT(.|)*"`

In order for it to get properly imported, I have to escape the backslash, i.e. `"INT(.|\\n)*"`

Is this by design, or is this a bug?

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan
