### ISSUE TITLE
Invalid HTTP endpoint encoding detected

### ISSUE THREAD

**Issue by koxon** [awslabs/aws-apigateway-swagger-importer#71]
Hi,

I created this entry in the forum.
https://forums.aws.amazon.com/thread.jspa?messageID=682500&#682500

When my endpoint contains encoded characters API Gateway rejects it.
Do you guys have some ways of inquiring about this on your end?

Thanks

**Comment by rpgreen** [comment]
This is a service issue - closing this and will have someone look into the forum post.

**Comment by koxon** [comment]
Thanks Ryan. I appreciate the escalation.
