### ISSUE TITLE
[Feature Request] - Publish this code as a library so it can be leveraged to create build script plugins.

### ISSUE THREAD

**Issue by mrburrito** [awslabs/aws-apigateway-swagger-importer#73]
I'm trying to automate deployment of API Gateway+Lambda functions from a Gradle script. It would be great to have this application published as a library and/or Maven and Gradle plugins so I can make it a standard, repeatable part of my build.

**Comment by jackie-scholl** [comment]
+1. I would love a Maven plugin, right now I'm having to use the Maven exec plugin to run the jar, which is very brittle

**Comment by mrburrito** [comment]
I'm working on an alternate plugin right now. The Gradle plugin works but no support for Maven yet. I want to update the documentation before I publish it to Maven central/Gradle plugin repository but you can clone it and build locally or deploy to a private repo and it will run.

https://github.com/mrburrito/gradle-aws-apigateway-plugin

**Comment by jjmartin** [comment]
i'd also like somthing in the way of build plugins for gulp or npm or other JS as my project is more lambda and node js centric and having a dependency on doing a build in java isn't something i really want.

**Comment by etzlers** [comment]
+1 for a build plugin for gulp or npm.

**Comment by austencollins** [comment]
@jjmartin @etzlers Have you seen Serverless (formerly JAWS) -> [serverless.com](http://www.serverless.com)  We're working on Java and Python support in the next few weeks.

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan
