### ISSUE TITLE
Auth "none" for x-amazon-apigateway-auth

### ISSUE THREAD

**Issue by austencollins** [awslabs/aws-apigateway-swagger-importer#8]
Hi Ryan, 

How is this feature coming along?  I'm really excited about this tool, but I'm not using any API Gateway Authorization, so I can't use it yet :(  I've got this weekend free to work (GF is out of town), so I'm hoping you guys can pull through before then!

Either way, I still love you guys.  Keep up the good work. 

Cheers

**Comment by rpgreen** [comment]
We pushed a service update yesterday so this should be supported now. Let me know if you have any issues. Thanks for the support!

**Comment by austencollins** [comment]
Thanks Ryan!  I'll dig into it this weekend.  Super excited about all of this.  Great work :+1:

**Comment by vidhim** [comment]
"x-amazon-apigateway-auth" :
{ "type" : "custom"}

it gives me an error - "Setting the authorization type to CUSTOM or COGNITO_USER_POOLS requires a valid authorizer" 

I want to call custom authorizer function any idea how to do that!!! 

Thanks in advance.
