### ISSUE TITLE
Support for $ref '#/responses/MyResponse'

### ISSUE THREAD

**Issue by arabold** [awslabs/aws-apigateway-swagger-importer#80]
From my tests it seems that the importer doesn't support references to responses like this:

``` javascript
    ...
    "paths": {
        "/myfunc":  {
            "get": {
                "summary": "Bla bla bla",
                "responses": {
                    "200": {
                        "$ref": "#/responses/MyFuncResponse"
                    }
                },
                "x-amazon-apigateway-integration": {
                    ...
                }
            }
        }
    }
    ...
    "responses": 
    {
        "MyFuncResponse": 
        {
            "description": "Bla bla bla",
            "schema": 
            {
                "type": "#/definitions/MyModel"
            }
        },
    }
```

The resulting resource for "`myfunc`" will not make use of the "`MyModel`" model as expected, but will have an undefined return value.

This looks like a bug/missing feature to me. I'm going to look into the problem, but do you have any comments on this?

Here's why I think this _should_ be supported: https://github.com/swagger-api/swagger-spec/blob/master/guidelines/REUSE.md

**Comment by arabold** [comment]
I did some debugging and it seems, that the problem originates somewhere in Swagger. The following call to `op.getResponses()` in `ApiGatewaySdkSwaggerApiImporter.java:410` returns an empty response object:

```
        updateMethodResponses(api, method, modelContentType, op.getResponses());
```

So either I'm doing something wrong in my definition (most likely) or that is a bug in Swagger (rather unlikely I would guess). Any suggestions?

**Comment by rpgreen** [comment]
I'm not sure if this is supported in Swagger - may want to ask swagger-core/swagger-parser and reference this issue

**Comment by arabold** [comment]
I guess we can close this issue, as I've found this: https://github.com/swagger-api/swagger-parser/issues/122

Seems the parser really did not handle response references. From my understanding of the importer code, with the new version of the parser this should work out of the box now.
