### ISSUE TITLE
Error while executing from HEAD

### ISSUE THREAD

**Issue by franksl** [awslabs/aws-apigateway-swagger-importer#86]
Hello,
After i run mvn assembly:assembly when trying to execute aws-api-import.sh I get this error:

Error: Unable to access jarfile build/maven/aws-apigateway-swagger-importer-1.0.1-jar-with-dependencies.jar

I suppose it's due to last commits that change deployment targets.
Thanks,
Franco

**Comment by rpgreen** [comment]
Thanks for reporting. Fixed
