### ISSUE TITLE
allOf not interpreted ?

### ISSUE THREAD

**Issue by koxon** [awslabs/aws-apigateway-swagger-importer#93]
Hi,

Not sure if the issue is on the importer or API Gateway side.

I am using `allOf` in my swagger Model definitions.

Simple example:

```
  GenericUser:
    type: object
    required:
      - data
    allOf:
      - $ref: '#/definitions/Generic'
      - properties:
          data:
            $ref: '#/definitions/User'
```

The GenericUser Class located in the generated SDK, only contains the "data" field and not the fields from the Generic Model. There are not combined.

If models are referenced only in the allOf, then no Model class will be generated at all.

For example:

```
UsersList:
    type: object
    description: List of Users object as returned by Orchestrate.io
    allOf:
      - $ref: '#/definitions/Generic'
      - type: object
        required:
          - data
        properties:
          data:
            $ref: '#/definitions/Users'
```

This will not generate a "Users" model at all but the Model is still referenced in the UsersList generate class:

```
import tv.sportarchive.model.Generic;
import tv.sportarchive.model.Users;

/**
 * List of Users object as returned by Orchestrate.io
 **/
public class UsersList extends Generic{
    private Users data = null;

    /**
     * Gets data
     *
     * @return data
     **/
    public Users getData() {
        return data;
    }

    /**
     * Sets the value of data.
     *
     * @param data the new value
     */
    public void setData(Users data) {
        this.data = data;
    }

}
```

There is no object "Users" in my SDK.

Please advise 

thank you
koxon

**Comment by kahouieong** [comment]
Can you confirm the model "Users" is created in API Gateway?

**Comment by rpgreen** [comment]
Swagger/OpenAPI import is now generally available in the API Gateway [REST API](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api.html), the AWS [CLI](http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-rest-api.html) and all AWS [SDKs](https://aws.amazon.com/tools). You can also import and export Swagger definitions using the API Gateway [console](https://console.aws.amazon.com/apigateway/home). This release addresses many of the open issues and feedback in this repository.

I would encourage you to migrate your workflow to the standard AWS tools. aws-apigateway-importer will receive minimal support from the API Gateway team going forward.

Any feedback or issues with the new importer should be directed to the official API Gateway [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

Thanks,
Ryan

**Comment by tasneem93** [comment]
@koxon were you able to resolve your issue? I am trying to use the "allOf" in my swagger file and it fails to deploy to API Gateway even though it does generate the models fine.

**Comment by tomkerswill** [comment]
I also see the same thing; and I'm using Swagger as well. The object which contains the allOf directive doesn't seem to get read at all. In the web console, the model simply does not show this object.
