### ISSUE TITLE
StageVariables lambda and role causing BadRequestException

### ISSUE THREAD

**Issue by cast** [awslabs/aws-apigateway-swagger-importer#94]
Hi,

I was expecting the following to work when creating an api with the swagger importer:

"x-amazon-apigateway-integration": {
          "type": "aws",
          "uri": "${stageVariables.resourcelambda}",
          "httpMethod": "POST",
          "credentials": "${stageVariables.invoke_role}",
          ...
          }

However I am getting the following error: 
ERROR - Error creating API, rolling back
com.amazonaws.services.apigateway.model.BadRequestException: Invalid ARN specified in the request

Since the documentation about stageVariables says that you should first create an api, deploy it once and then you can use stage variables does this mean that this is incompatible with having the stageVariables in the swagger integration object?

**Comment by rpgreen** [comment]
There are some restrictions on where stage variables can be used in a URI and an ARN.

They must be in this form:

URI:
"arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda::ACCOUNT_ID:function:${stageVariables.functionName}/invocations");

Credentials:
arn:aws:iam::ACCOUNT_ID:${stageVariables.roleName}

We will look into improving the documentation on this.

Thanks,
Ryan
