### ISSUE TITLE
Look for credentials in current working directory

### ISSUE THREAD

**Issue by phillip-haydon** [awslabs/aws-apigateway-swagger-importer#96]
Right now it looks like you force looking for credentials in the home directory and do not look for credentials in environment settings or current working directory.

http://docs.aws.amazon.com/AWSSdkDocsJava/latest/DeveloperGuide/credentials.html

Could you please fix the credentials so that they can be found in the current working directory in .aws/credentials / config

And implement support for environmental variables.

---

I'm not a Java developer other wise I would send you a PR :cry:  . Reason I'm requesting this is for use in Team City where credentials need to be different for different build projects. 

:( I literally cannot get this to run in Team City on Windows because of the way you load credentials. 

Works 100% fine running manually.

**Comment by rpgreen** [comment]
If you update to latest you should be able to use credentials in environment variables or system properties. See http://docs.aws.amazon.com/AWSSdkDocsJava/latest/DeveloperGuide/credentials.html

**Comment by phillip-haydon** [comment]
Thanks @rpgreen, I looked at the commits and see you added it 2 days ago, I built the jar like 3 days ago. Hah.

Thanks. Will update and re-test.

Thanks.

**Comment by phillip-haydon** [comment]
@rpgreen it works perfectly now!

Do you have any problem if I setup a build of aws-apigateway-importer on Team City for Windows and host a nuget of the jar file on www.nuget.org?
